### ISSUE TITLE
Books Search Queries Lack or Show Nothing In Comparison To OpenLibrary

### ISSUE THREAD

**Issue by seniorm0ment** [bookwyrm-social/bookwyrm#1011]
**Describe the bug**
Not entirely sure if this is a bug, or if instances are allowed to do some sort of genre limiting. If the latter, it should be specified somewhere on the instances sites which genres are whitelisted. But I believe this may be a bug, or something else.
Basically when searching in BookWyrm (tried 2 of the instances), books that show up in OpenLibrary, do not appear in BookWyrm searches.
For the following, sections, I'll use https://openlibrary.org/works/OL17371431W/ThinkPad as my primary example.

**To Reproduce**
1. Go to https://openlibrary.org/
2.  Search 'thinkpad' (https://openlibrary.org/search?q=thinkpad&mode=everything)
3. See results
4. Go to https://bookwyrm.social/ or other instance
5. Search 'thinkpad'
6. no results (not even anything, openlibrary offers multiple results)
7. try isbn13, try isbn10, still no results.

**Expected behavior**
List all the same content fetched when viewing from OpenLibrary directly
https://openlibrary.org/search?q=thinkpad&mode=everything

**Desktop (please complete the following information):**
    - OS: Artix Linux
    - Browser: Librewolf
    - Version: 88

**Additional context**
Some queries such as 'Dune' show up.
But it seems to be a toss as to whether I get results or not.

As per the BookWyrm wiki, it states "The application is set up to share book and author data between instances, and get book data from arbitrary outside sources. Right now, the only connector is to OpenLibrary, but other connectors could be written."
So I would expect to see the same searches.

Some other searches with no results, or lacking results:
https://openlibrary.org/works/OL8747011W?edition= (https://bookwyrm.social/search/?q=Lenore)
https://openlibrary.org/search?q=players+handbook&mode=everything (https://bookwyrm.social/search/?q=Player%27s+Handbook)

**Additional Context 2**
Now what confuses me, and is why I originally mentioned that I was unsure if this was a bug, or not is due to the greatly differing results between two instances.
https://bookwyrm.social/search/?q=Dune
https://bookclub.techstartups.space/search/?q=dune

So I'm wondering if there is some kind of genre whitelist/blacklist functionality? If that is the case, then it should be made clear on the front page of the instance somewhere. I would also suggest setting the "main instance" or providing a "second instance" which has all books enabled if this is the case. Any other instance hosts can then go from there and limit what they want to "theme" their sites around the content. I personally can't say I entirely understand the point of disabling search for specific genres, you can still theme the content  of the instance around it without restricting search-ability. But ok, It would be appreciated to have at least one instance that "has everything", which doesn't currently seem to be the case?

But still, it is not entirely clear to me. As searching 
https://openlibrary.org/search?q=Do+Androids+Dream+of+Electric+Sheep%3F&mode=everything
brings up lots of results,
but on bookwyrm only a few
https://bookwyrm.social/search/?q=Do+Androids+Dream+of+Electric+Sheep%3F
Despite being the same genre?
So Idk, I'm thinking this is a bug. But clarity would be appreciated.

**Comment by mouse-reeve** [comment]
Hi, thank you for raising this! Let me explain a little about how search works and the relationship between different instances:

A BookWyrm instance starts out with no book data, and books are only added when uses import them from an outside data source (currently, this is always OpenLibrary), or when they receive info about a book from another instance. So there are millions of books in OpenLibrary that don't exist in any one BookWyrm instance, and not every instance has the same books in it. 

There aren't any allow- or blocklists in play, it's just a matter of what books are loaded in that instance. That's why techstarups.space, which is a smaller instance than bookwyrm.social and not focussed on fiction, only has one result for `Dune`, whereas bookwyrm.social has many. 

As a logged-in user, however, you can import any book you want if it's available in OpenLibrary, and the search results form there will show up below the local search results. This is limited to logged in users so that the instance can have a little more control over what is added to their database. Instances may also clean up and deduplicate their book data, so the catalog won't be exactly the same as OpenLibrary's.

Here's what I see as a logged in user for https://bookwyrm.social/search/?q=Lenore:
<img width="489" alt="Screen Shot 2021-04-28 at 12 12 15 PM" src="https://user-images.githubusercontent.com/1807695/116459769-1253d780-a81b-11eb-8773-3e5dac717566.png">

**Comment by seniorm0ment** [comment]
Ah okay, that makes sense, and I wasn't logged in so yeah understandable

Maybe it would make sense to:

- Provide the results from OpenLibrary for non-logged in users as well instead of hiding it, if they click the import button provide a popup stating it's for registered users only or something.

- Make this more clear on the Github readme

What happens if you click the title of the results from OpenLibrary? Does it simply take you to the OpenLibrary page? Or does it open it in Bookwyrm?
I would assume it only opens it in Bookwyrm after it is imported? 
It would make sense to me that it could open it in Bookwyrm and act as a frontend for OpenLibrary to nicely show the results.

Anyways, I still think these results shouldn't be hidden to un-registered users.

**Comment by seniorm0ment** [comment]
Are editions supposed to be shown?
For example, if I am reading the Signet edition of [1984 ](https://openlibrary.org/works/OL1168091W/)(ISBN13: 9780451524935), that doesn't appear at all on bookwyrm (even when logged in - https://bookwyrm.social/search/?q=1984).
I see https://bookwyrm.social/book/38008 and https://bookwyrm.social/book/15151 however neither of those ISBN's match up. There are no other George Orwell 1984 editions listed in the search under the other catalog area.

Do I have to manually add a book? In that case, will simply inputting the Openlibrary key and clicking save fetch all the information for that edition, seeing it already exists on OpenLibrary?
(Seems like bookwyrm should just show edition results though)

**Comment by mouse-reeve** [comment]
BookWyrm only grabs some of the first 50 editions (the first page returned). There's no reason it has to only grab the first 50, I just didn't add that, and I ought to.

If you search for the specific isbn and import that result from OL, you will get that exact edition imported, and it should connect it to the right work (I just did that on bookwyrm.social with 9780451524935 to make sure I was right, so that edition is now present in bookwyrm.social).

When you import a book, and the other editions are grabbed, it will ignore some editions in OpenLibrary if the metadata quality is too low (I don't recall exactly what the parameters are, but it will accept anything with a cover or isbn, among some other things). 

In terms of which result gets shown, if you do an isbn search (or a search on another unique identifier, like openlibrary key), it will show you the exact edition. But if you search based on title and author, it will pick the best match edition, which is based on how close the text of the title is to the search query, and how much metadata is available for the edition. So if there are 50 editions of 1984, all with the same title and author, it will present the one that is considered the "default" based on its metadata. The process of picking the "best" or "default" edition to show is something I'm working on improving at the moment.

**Comment by seniorm0ment** [comment]
>If you search for the specific isbn and import that result from OL, you will get that exact edition imported

Ah okay. I do notice however https://bookwyrm.social/book/123932 does not show any information such as what OpenLibrary shows in regards to "An edition of Nineteen Eighty-Four (1949)". I do see the 52 editions list, however yes I think it should grab them all.

I do think overall this search could be improved upon, as users who do not know the ISBN or may want to browse a bit can only see these results if they're imported, otherwise they need the ISBN. 
Maybe under the results if other editions are linked to a result, have it say "other editions" as there is room. 
Or at least maybe it might make sense to put another search box stating something like "For Specific Edition search, enter ISBN" or something.

Another option might be best to prioritize showing "Series" results instead of specific editions on the search. Otherwise you have like multiple 1984 listings and it can be a bit confusing.

**Comment by mouse-reeve** [comment]
> I do notice however https://bookwyrm.social/book/123932 does not show any information such as what OpenLibrary shows in regards to "An edition of Nineteen Eighty-Four (1949)".

Can you clarify what you mean by this? There's quite a bit of information about each edition present in the editions list (https://bookwyrm.social/book/37980/editions)

**Comment by seniorm0ment** [comment]
>Can you clarify what you mean by this? 

For example, in OpenLibrary you have the root work and then it shows editions. 
Bookwyrm shows this properly via your link, however I am suggesting adding "An edition of Nineteen Eighty-Four (1949)" directly above that "see 52 editions" directly on the book page for clarity sake.
Currently it is at the top of https://bookwyrm.social/book/37980/editions

However also the book that that links to is https://bookwyrm.social/book/37980 which isn't entirely the best result imo.
From what I can tell, OpenLibrary has a "root edition", such as https://openlibrary.org/works/OL1168091W/Nineteen_Eighty-Four
then all editions show "An edition of [Nineteen Eighty-Four (1949)](https://openlibrary.org/works/OL1168091W/Nineteen_Eighty-Four)". So I'm suggesting do a similar thing on Bookwyrm, and use the link they use.

To be clear, this is also what I was suggesting when I had suggested clarifying the results in the search. Use that root edition if it is available, instead of displaying random editions. You show the "generic"/"root" edition, then users can check out editions further from there and add what edition they want. Just a bit cleaner imo.
>Another option might be best to prioritize showing "Series" results instead of specific editions on the search. Otherwise you have like multiple 1984 listings and it can be a bit confusing.

**Comment by seniorm0ment** [comment]
Relating to my original confusion about imports, after a book is imported does it grab updates if there are any edits made to that from OpenLibrary?
Also I have noticed that some imports don't show the "by" field, despite being present on OpenLibrary.
I can open a new issue for this if you want, just didn't want to spam issues to the Github . Thanks :)

**Comment by mouse-reeve** [comment]
> Relating to my original confusion about imports, after a book is imported does it grab updates if there are any edits made to that from OpenLibrary?
> Also I have noticed that some imports don't show the "by" field, despite being present on OpenLibrary.
> I can open a new issue for this if you want, just didn't want to spam issues to the Github . Thanks :)

There are existing issues for these, #591 and #850
