### ISSUE TITLE
Re-thinking timelines

### ISSUE THREAD

**Issue by mouse-reeve** [bookwyrm-social/bookwyrm#1063]
Right now, BookWyrm uses the same paradigm for timelines that Mastodon uses. I've never been very happy with this - mainly because I think the local and federated concepts can be confusing to users who aren't already big nerds (said with love) about federation or used to Mastodon. I also don't get a lot of utility from it - both on mastodon and bookwyrm, I pretty much only look at my home timeline. 

To get specific about what the timelines are, how they work, and my own feeling on them:

### Home timeline
Your default timeline, which shows you posts and boosts from users you follow anywhere in the fediverse
 
This works well for me because it shows me content from users who I specifically opted in to seeing. It is familiar from just about every form of social media, and I think it's clear to new users what to expect to see here.

The main pain point that I see with this is that new users see absolutely nothing here, and it's hard to know how to get started and find out what is going on. The local and federated timeline show you activity and give you a place to start. In mainstream social media, this is often addressed through suggesting people to follow in ways that aren't good for user privacy (like going through your contacts), or in ways that lead to "influencers" (like suggesting high-follower-count users to everybody).

 ### Local
Any post (but not replies), with privacy set to public, from non-blocked users

I think there can a benefit here for small, tight-knit instances because it provided a way for new users to see activity specific to that community. Personally, this doesn't work for me in practice - I'm on a small tight-knit mastodon instance, but I just follow the majority of users and never use the local timeline.

On a larger, general-purpose instance like bookwyrm.social, I see less benefit and less distinction between local and federated timelines.

### Federated:
Any post (but not replies), with privacy set to public, from non-blocked users on any instance federated with your instance

On Mastodon, I find this timeline actively unpleasant - the posts aren't relevant to me, and don't feel like they were written with me (ie, a total stranger) as the intended audience. I've had negative experience with interactions on Mastodon that feel overly familiar or just unwelcomely out-of-the-blue in a way that I haven't on Twitter, and I suspect that the federated timeline is a contributor. When I browse that timeline, the UI is encouraging me to interact with posts from people who are very socially distant from me and taken out of the context they were written, and I rarely find that kind of interaction positive. 

## Alternatives
One alternative is to only have the Home timeline. This is what most social networks (twitter, facebook, goodreads, etc) do. Solely looking at my own use case, this is a perfectly good solution, but I'd like to know more about how other people feel about various timelines and how they'd like to see posts.

Another alternative is a "friends vs strangers" paradigm, in which there's the home timeline, and a timeline of any post that is _not_ by someone you know, regardless of which instance they are on. 

It's also possible to define a handful of different timelines, and let instance admins decide which ones to use. This gives instances more flexibility, but also means it's less clear to a user how their posts will be presented (a user on an instance that only uses the home timeline might be unpleasantly surprised to find out their posts are shown to everyone in a federated timeline on another instance, for example).

## What does success look like
I think a successful timeline UI would:
1. show you the posts you expect to see because of who you follow, 
2. allow you to discover posts near your existing social network
3. provide a way to get started when you don't know anyone

I'd really appreciate hearing outside perspectives on this - what feels like it works and what doesn't, ideas or grand dreams about what this should look like, or anything else.

**Comment by tastytea** [comment]
### Federated timeline, but with less clutter

I did use the federated timeline a lot when I started my account, and found many interesting books and book-readers that way. Two months later, I still look at it from time to time and sometimes I see something good that I wouldn't have seen otherwise.

I like the “friends vs strangers” idea, it would make the federated timeline more useful to me. I also think that boosts shouldn't be displayed there, because i think it should be irrelevant how many people like a thing.

I don't see a good alternative for discovering books & friends. Most books don't have topics, tags were hardly ever used when they were a feature, descriptions are often empty. How should an algorithm figure out what to recommend?

**Comment by bcj** [comment]
I only ever use home timeline so I'd personally be fine with removing the others.

In terms of other timelines I'd maybe consider looking at:
* public (or by friends) posts about books I'm currently reading
* public (or by friends) posts about books I've previously read
* maybe public posts by friends-of-friends?

**Comment by tastytea** [comment]
Maybe matching could be done based on ratings. When a person rates a book with 4 or 5 stars, recommend them other people that rated a book by the same author with 4 or 5 stars?

**Comment by mouse-reeve** [comment]
It is totally technically possible to follow posts about a book in the same way you follow posts by a particular user. I worry, however, that this could over-expose people's public posts which weren't intended for mass consumption by strangers.

**Comment by mouse-reeve** [comment]
> * maybe public posts by friends-of-friends?

I like the idea of friends-of-friends a lot, I think it would make it easier to find people you already know but aren't connected to, and to find people you'd like to know.

**Comment by npdoty** [comment]
I anticipate that I would only regularly use the home timeline. 

But I do think the local and federated messages could still be useful, although maybe not presented as a timeline/feed. That is, when I'm thinking about reading a particular book, I'd be happy to read a summary of the federated and local posts about that book, when I view the page for that book. That wouldn't be subscribing to every update in real-time on a book, but the ability to on-demand scroll through reviews or interesting quotes that people have highlighted in it.

**Comment by cats-shadow** [comment]
> In terms of book discovery, my ideal is for people to get recommendations "manually" from friends, rather than algorithmically based on past reading activity.

At one time RuNet had a server Imhonet.ru, which had a very correct, in my opinion, algorithm of recommendations.
Each user has a profile of the scores he gave to the books he read. If the size of the intersection of the set of books read by two (or more) users exceeds a certain value (a constant in the algorithm settings), then the correlation of users' score profiles on this intersection of sets of books read is calculated.  If this correlation exceeds a certain value (also a constant in the algorithm settings), then we can assume that the users are close enough, and recommend something that was not included in the intersection of sets of books read, but received a high score.

**Comment by npdoty** [comment]
> I've considered this and I've been reluctant to expand what shows up for a book beyond reviews, because I want to make it possible to talk about books in a way that feels more casual and transient. I would feel daunted at the prospect of anyone who looks at a book seeing my passing thoughts on it that I posted three years ago (or similar), which is why right now only reviews are aggregated like that.

Right on to think about the privacy or feelings of appropriateness around how information is distributed, even if it's marked as public! 

For me, that's why the distinction is important between pushing something into a feed (where anyone on the instance or the federated timeline might see it brought to their attention) and having it available only if someone is specifically looking for comments/quotes about that book. Reviews vs comments/quotes is another way to make that distinction, though I don't see that difference in the UI.

I would not have guessed from the current UI that my public comments about a book do appear on the local and federated timelines (broadcast more widely than "unlisted") but won't appear for others who look at the book page.

**Comment by quaayd** [comment]
I don't quite understand the difference between local and federated on bookwyrm, because federated is still only book posts. I do like to glance at the federated timeline sometimes because it exposes me to books that i may have missed. I prefer my home feed to be small; i don't follow many users because i feel overwhelmed by too much info and then it feels random.

I would like a feed that is somehow related to books in my lists, reviews and comments, that would seem more useful than the local feed. but i also like the idea of posts expiring and disappearing eventually.

**Comment by kopischke** [comment]
> Each user has a profile of the scores he gave to the books he read. If the size of the intersection of the set of books read by two (or more) users exceeds a certain value (a constant in the algorithm settings), then the correlation of users' score profiles on this intersection of sets of books read is calculated.

That assumes everybody’s ratings are on the same scale. As someone whose rating system is persistently skewed against the implicit (or even sometimes explicit, ahem, Trakt) rating weights of services for the sake of internal and chronological consistency, I’d very much dispute that assumption.

**Comment by cblgh** [comment]
_(Pardon this for being unrelated to the letter of the question, but I believe it is relevant to the spirit of it!)_
btw i've **bolded ideas**, to make this reply easier to skim (this is a surprisingly active comment thread!!)

I would like to see **timelines on books**! 

E.g. if readers `cervantes` and `bookchin` comment on the Tao Te Ching, I'd love to see those **comments collated under the book's overview page**. Probably makes sense to only see those comments if they are from people I follow || people on my instance? Not sure how to slice it.

Otherwise, I mostly use the Home view, some times dipping into the view of a particular reader to see if they've been reading or posting anything interesting :~ 

When I was getting started with my account, I'm pretty sure I browsed the local view & individual users to find & follow people with tastes overlapping mine. Perhaps you can solve this dicoverability problem by some kind of **invite link**, automatically following the person who sent it, or at least directing you to.. their local view? their profile view?

It could be interesting to see **timelines from the point of view of another person**, as an option when you go to their profile? (Visitor's timeline?)

I actively avoid the federated view whenever I can in Mastodon, kinda totally missed it existing in bookwyrm x)

**Comment by cats-shadow** [comment]
@mouse-reeve 
I finally got around to looking into bookwyrm timelines.
Everything looks usable to me, except for the lack of message type filters, which I would like to exclude from the timeline. For example, "started reading", "finished reading", "rated", "reviewed", "added book".
If it were possible to quickly adjust such filters (and save the settings) - it would be very nice.
And it would be great to be able to exclude own statuses from display in timelines. I already know what I've read, what book I wrote a review for, or how I rated the book. :

**Comment by dlowe-net** [comment]
I'm late to the party now, but I wanted to mention that at least on Mastodon, Local feeds are how smaller instances maintain a sense of community. People on the larger instances (like mastodon.social) don't see its utility because on those instances it's indistinguishable from the Federated timeline. For instances with <1000 users, however, the Local feed is where you get the "flavor" of an instance.

**Comment by mouse-reeve** [comment]
> I'm late to the party now, but I wanted to mention that at least on Mastodon, Local feeds are how smaller instances maintain a sense of community. People on the larger instances (like mastodon.social) don't see its utility because on those instances it's indistinguishable from the Federated timeline. For instances with <1000 users, however, the Local feed is where you get the "flavor" of an instance.

Thank you! I really value smaller instances and want to prioritize features that facilitate them. As a user of a smaller (around 50 person) Mastodon instance, I haven't gotten utility from the local timeline, but that's what it's so helpful to hear from other people. Can you tell me more about how you personally use the local timeline? For example, is it something you used to get oriented when you first joined, or something you use regularly? Do you find posts there that you don't find in your home timeline?

(And as an aside, the change I made in #1253 does leave a path for admins to re-enable a local timeline.)

**Comment by mouse-reeve** [comment]
A possible alternative to a local timeline is creating a "discover" view for logged in users that shows local posts (as per #1144) - this would look a little different than a timeline and not be part of the tabs that show available timelines, but still give you the "local flavor" but displaying public activity in your instance.

**Comment by dlowe-net** [comment]
The local timeline may be more of a themed instance sort of thing, where people are talking about aspects of common interest. I end up using it as much as my home timeline. It's a place where you don't have to follow users because you are already reading them. If the local timeline is full of uninteresting noise, its utility declines, but if it's full of interesting things, it becomes the town square of the instance.

However, bookwyrm isn't mastodon, and I think instance-based communities are going to look a bit different, since the interactions between people are going to be different. Something like a local timeline might do nothing here. I think it'd be nice to fantasize about what sort of features would help an instance to thrive, if it were themed around location, genre, or language.

**Comment by mouse-reeve** [comment]
Major thank you to everyone who participated in this discussion, it was immensely helpful and I appreciate the care and thought everyone brought! The timelines are now updates to reflect this conversation so I'm closing this issue. But of course that doesn't mean feedback and ideas are closed. Please feel free to open an issue or discussion topic if you have additional thoughts or feature requests ❤️
