### ISSUE TITLE
Hashtag support would be nice

### ISSUE THREAD

**Issue by eldang** [bookwyrm-social/bookwyrm#1081]
**Is your feature request related to a problem? Please describe.**
I take part in a book club on Mastodon that works by using a hashtag (#SFFBookClub) so we can find each other.  Since most of the traffic on that hashtag is discussions of the book we're reading each month, Bookwyrm seems like a natural home for those posts.  But I need to be able to both use hashtags in reviews and follow/search a hashtag in Bookwyrm for that to work.

**Describe the solution you'd like**

1. Hashtag support in my posts here - i.e. not stripping out the # and allowing it to be indexed
2. A view in which I can see posts with a given hashtag, like https://weirder.earth/tags/SFFBookClub on Mastodon.

**Describe alternatives you've considered**
For the time being I think my workaround is to post reviews here but link to them from my Mastodon account.  Not terrible, but a little clunky.

**Comment by hueyy** [comment]
A workaround for the time being is to use Guppe Groups, i.e. tag [@SFFBookClub@a.gup.pe](https://a.gup.pe/u/SFFBookClub) in your post and it will be automatically boosted by @SFFBookClub@a.gup.pe. You can then follow @SFFBookClub@a.gup.pe to view all posts tagging it.

**Comment by mouse-reeve** [comment]
@chdorner I'd be super super happy to support! You're on the right track with what you have, and I'll try and produce a more long-form answer tomorrow when it's not my bedtime :)

**Comment by mouse-reeve** [comment]
> Having had a look at how user mentions in statuses work, I was thinking of the following:
> 
> 1. New `bookwyrm_tags` table
> 2. New `bookwyrm_status_mention_tags` table
> 3. Parse tags in `CreateStatus.post` and add `mention_tags`

This all sounds right. You can see on the `Status` model that the [existing tags](https://github.com/bookwyrm-social/bookwyrm/blob/main/bookwyrm/models/status.py#L35) (`mention_users` and `mention_books`) use the custom model field type `TagField`, which handles [how the database field is translated to and from ActivityPub format
](https://github.com/bookwyrm-social/bookwyrm/blob/44941ffc9c8daaf8e4a2c94e69f6d321f9b839ec/bookwyrm/models/fields.py#L334). 

>   * Not having read the ActivityPub spec yet I'm assuming there is a rather standard way of defining hashtags that would also support proper hashtag linking within Mastodon and other ActivityPub software

This uses the `tag` field. It's also used for tagging users, so the `type` is important:
```
  "tag": [
    {
      "type": "Hashtag",
      "href": "https://example.com/tags/hello",
      "name": "#hello"
    },
```

All of BookWyrm's activitypub objects are defined by python dataclasses, and they live in the [`bookwyrm/activitpyub/` directory](https://github.com/bookwyrm-social/bookwyrm/tree/main/bookwyrm/activitypub). Tags are a type of [`Link`](https://github.com/bookwyrm-social/bookwyrm/blob/main/bookwyrm/activitypub/base_activity.py#L301) (not sure why I picked "link" here, tbh). You can see a little lower in that file that [mentions are a subclass of `Link`](https://github.com/bookwyrm-social/bookwyrm/blob/main/bookwyrm/activitypub/base_activity.py#L321), which I think is how hashtags would want to work as well.

Tagged users (mentions) [are associated with a `Note` objects](https://github.com/bookwyrm-social/bookwyrm/blob/main/bookwyrm/activitypub/note.py#L35), which all the other types of post (like reviews, etc) inherit from. 

> * Import tag mentions into local DB when receiving ActivityPub statuses

This should happen [when the ActivityPub is serialized into a model](https://github.com/bookwyrm-social/bookwyrm/blob/main/bookwyrm/activitypub/base_activity.py#L160), and shouldn't need to be coded explicitly. It may be necessary to modify how [TagField behaves](https://github.com/bookwyrm-social/bookwyrm/blob/44941ffc9c8daaf8e4a2c94e69f6d321f9b839ec/bookwyrm/models/fields.py#L356), but I haven't thought enough to be sure.
 
> Open questions:
> 
> * Should there already be a way to list statuses by hash tag (i.e. linking to that page from hashtags in statuses)

I think so! But I would do this as a separate feature because it will be complicated by privacy settings and I don't think it's strictly necessary to get the feature mostly working.

  
>   * if yes, per user or across the whole instance?
I think it would be most helpful to see it across all users, since I think the goal of tags is to discover other posts.

>   * is there already a page that I could use for inspiration that shows statuses across different users?
Only the "discover" page, which tbh I think needs a lot of UI work to be more visually legible.

**Comment by mouse-reeve** [comment]
The activitypub code is really convoluted and hasn't had much airing out or eyes besides mine on it, so I'm happy to clarify things further and refactor as needed.
