### ISSUE TITLE
Equal cover size in the feed for different statuses about one book

### ISSUE THREAD

**Issue by cats-shadow** [bookwyrm-social/bookwyrm#1082]
Now the cover size displayed in the feed is different for different types of statuses about the same book, see the screenshot (rated and reviewed statuses).
Is it possible to make the cover size displayed in the feed the same for all types of statuses about the same book?
![2021-05-12_23-16-06](https://user-images.githubusercontent.com/16667173/118039384-f3a42380-b378-11eb-8cb6-4e0dfdd1e26a.png)

**Comment by cats-shadow** [comment]
![2021-05-12_23-25-28](https://user-images.githubusercontent.com/16667173/118039861-788f3d00-b379-11eb-8d0d-fc6562b1a226.png)

**Comment by mouse-reeve** [comment]
This was an intention change added somewhat recently. You can see the conversation behind it here: https://github.com/bookwyrm-social/bookwyrm/issues/964

The goal was to give more space and prominence statuses in which the poster says something (makes a comment, writes a review, etc), and less prominence to passive activities like starting and finishing a book. Cover size is often the limiting factor in the length of a status, which is why two sizes are used.

Can you tell me more about what isn't working for you about having different cover sizes?

**Comment by cats-shadow** [comment]
> Can you tell me more about what isn't working for you about having different cover sizes?

The different sized covers in the feed don't affect usability, but in my case, they hurt the aesthetic perception. No more than that.

The size of the cover image does not matter. Of the two size options currently in use, the smaller one is fine, too, for example. But when both sizes are in a feed it spoils the look, IMHO. It would be nice to select the same size somewhere in the configuration, then the user/admin could choose the look that suits them.

**Comment by mouse-reeve** [comment]
I'm going through and closing old issues that seem stale or out of date - feel free to reopen with a comment adding some updated context if you feel like it still needs to be addressed ❤️
