### ISSUE TITLE
Books without ISBN are often missed in csv imports

### ISSUE THREAD

**Issue by justinabrahms** [bookwyrm-social/bookwyrm#1262]
As mentioned in Element ( https://matrix.to/#/!zoxBMxLlvIyeEKkHuB:matrix.org/$2BYBCdDorUOtJgwsbP_qZh6We6stEZ-Gy4KIDJ-KKOk?via=matrix.org ), I was unable to import a few things with subtitles. This is the a portion of the list. The format of the list is the text of the thing from goodreads & the link to it in the system. The remainder are on import 604 on the flagship instance.

- "Project to Product: How to Survive and Thrive in the Age of Digital Disruption with the Flow Framework by Mik Kersten" https://bookwyrm.social/book/164013
- "Intuitive Eating: A Revolutionary Anti-Diet Approach by Evelyn Tribole" https://bookwyrm.social/book/164015
-  "The Journal of Best Practices: A Memoir of Marriage, Asperger Syndrome, and One Man's Quest to Be a Better Husband by David Finch" https://bookwyrm.social/book/164017
- "Titan: The Life of John D. Rockefeller, Sr. by Ron Chernow" https://bookwyrm.social/book/151916
- "Accelerate: The Science of Lean Software and DevOps: Building and Scaling High Performing Technology Organizations by Nicole Forsgren" https://bookwyrm.social/book/89924
- "Multipliers, Revised and Updated: How the Best Leaders Make Everyone Smarter by Liz Wiseman" https://bookwyrm.social/book/164024

**Comment by mouse-reeve** [comment]
Huh! These are all books that have isbn numbers, so they should be matched based on that, not by title. Are the isbns present in the csv you uploaded?

**Comment by justinabrahms** [comment]
Here's the associated CSV.
[goodreads_library_export.csv](https://github.com/bookwyrm-social/bookwyrm/files/6952533/goodreads_library_export.csv)

**Comment by mouse-reeve** [comment]
Ah okay, it looks like these don't have ISBNs in the spreadsheet - kindle editions seem to be a common denominator as well. Another user has also reported that un-matched search results are from kindle-specific entries.

The issue appears to be that search results against the local index are producing very very low confidence ratings, even on queries that seem like they're as close as humanly possible. This is a side effect of https://github.com/bookwyrm-social/bookwyrm/pull/1199 - the import requires a confidence of 0.999 to accept a match, but producing search results way below that.

For example:

"Project to Product Mik Kersten" -> 0.29
"Project to Product: How to Survive and Thrive in the Age of Digital Disruption with the Flow Framework Mik Kersten" -> 0.15

**Comment by mouse-reeve** [comment]
I'm not sure off the top of my head how to fix this because I'm not sure why the confidence ratings dropped so precipitously when I refactored the search index. Either the confidence ratings produced in Postgres need to be changed to be more reflective of what a person would perceive as accurate, or the threshold for approving an import match needs to be lowered to reflect a different confidence scale.

The reason this is tricky is that the one outcome that's worse than books that clearly should match not matching is when they match incorrectly, and user's data is silently added to the wrong book. At least in the former case, nothing incorrect is added and it's clear what went wrong.

**Comment by justinabrahms** [comment]
We might be able to completely side-step this problem with some UI tweaks.  "Hey, we didn't find that book. Here's the book that's the closest match. If it seems right, click this checkbox and we'll use that"

That said, having regression tests on the search index sounds both difficult and useful.

**Comment by mouse-reeve** [comment]
Oh yeah! That's a really good point!

**Comment by mouse-reeve** [comment]
It turns out there was a bug prevent any title/author search results from matching - once the fix is live, it'll be worth re-trying the unmatched entries. The UI you suggested is still a very good idea, but this will at least improve the situation on a quicker time scale: https://github.com/bookwyrm-social/bookwyrm/pull/1279
