### ISSUE TITLE
Support separate Print and Ebook ISBNs

### ISSUE THREAD

**Issue by lilyball** [bookwyrm-social/bookwyrm#1368]
**Is your feature request related to a problem? Please describe.**
When adding a new book, I’m asked for the ISBN. It does not specify whether it should be the Print or Ebook ISBN, and does not allow me to specify both.

**Describe the solution you'd like**
It should prompt for both Print and Ebook ISBNs so I can fill in both (and so it’s obvious which ISBN to enter).

**Describe alternatives you've considered**
It could just specify Print ISBN, but then we wouldn’t have Ebook ISBNs.

**Comment by mouse-reeve** [comment]
The precedent in the data model is to add the print and ebooks versions as separate editions of the same work. It should be much more obvious how to create an alternate edition, though

**Comment by lilyball** [comment]
When adding a book I didn't see any field that would be used to distinguish between the print and ebook versions. There were two fields for asking about details of the print edition (format and pages) but that's it.

Also, if these are separate editions, that means pretty much every book published in the past decade and going forward needs two editions that are identical in all respects except for ISBN and whatever is used to identify ebook vs print. That's going to be very tedious.

**Comment by mouse-reeve** [comment]
The reason I've been doing it that way is that is how the data is imported from the external catalogues (OpenLibrary and Inventaire) - but I hear you that it's frustrating to add a bunch of variations when you do have to manually add a book, or the edition you want isn't already in the system.

The field that differentiates them (besides ISBN) is "Format" -- I'm working on a change to make that a drop-down list (#1113) which will make that clearer to use.

**Comment by lilyball** [comment]
The Format field was listed under “Physical Properties”. If it’s meant to support Ebook then that’s a bit of a confusing labeling.

**Comment by mouse-reeve** [comment]
Yeah it is!

**Comment by mouse-reeve** [comment]
Thank you for filing this, I really appreciate hearing about parts of the UI that are frustrating or confusing. My takeaways are that
1. it's a hassle to add alternative editions of a book,
2. it would be nice to create books that are identified by multiple isbns, and
3. "format" is a confusing field

The workflow for creating new books needs a lot of love.

**Comment by lilyball** [comment]
Yes to all of that! And as an aside, this is one of the most positive responses I’ve ever had to filing an issue on a GitHub project 😄 You’re explaining why things are how they are now, you’re telling me what you’re hearing and your takeaways, and you are making me feel good about filing this issue. Thank you! 💕

**Comment by hughrun** [comment]
Having separate records for each edition & format is correct, I think. Print and ebook is just one example where you have multiple editions of the same work, and being able to identify a specific edition is important to some people depending on the context. However this is not necessarily obvious to everyone and as @lilyball notes the workflow is potentially tedious for new books where multiple formats or languages are published simultaneously. Some suggestions:

1. Change `Physical properties` to `Format` and then `Format` to, perhaps, `Physical Format` (maybe, though perhaps this is no clearer);
2. Adjust the workflow for adding a brand new item so the user is asked what format the book is in right up front, and then the options available in the form change and in some cases are pre-filled depending on that format. e.g. if you select `Audiobook` we don't display the `Pages` field because it's irrelevant. This _possibly_ will improve clarity;
3. Add a button in the book editing screen to create a new edition (different language, different format, whatever) by making a copy of the existing record. That way in this example @lilyball could create a record for e.g. the paperback version and then easily create a second record by essentially just getting a copy of the original record and changing the format to ebook and adjusting the ISBN (i.e. just change the details that are different). A variation of this is how libraries create catalogue records all the time.

**Comment by mouse-reeve** [comment]
I think this has mostly been addressed by subsequent changes in the last couple years. There are bits of it that haven't, but I think there are more recent issues touching on them. I'm going to close this mostly because it's gotten quite stale, but I really appreciate the feedback, and if anyone in the thread still has lingering changes they want made, I'd be super super appreciative of a new issue about it. Thanks all ❤️
