### ISSUE TITLE
A Clearer Wording for the Invitation Requesting Form

### ISSUE THREAD

**Issue by oragegu** [bookwyrm-social/bookwyrm#1417]
**Is your feature request related to a problem? Please describe.**
When an instance opts for "invitation request", the wording of the request form might make one thinks that it's a direct email exchange with the admin.

**Describe the solution you'd like**
A clearer wording for the invitation request form.

**Comment by mouse-reeve** [comment]
Thank you!

There are a few different states for the registration page. When you allow invite requests, this is the default display:
<img width="488" alt="Screen Shot 2021-09-18 at 9 57 06 AM" src="https://user-images.githubusercontent.com/1807695/133897569-0db691e5-f875-4519-933c-cd92a99f84a3.png">
The "contact an administrator to get an invite" text can be set by the instance admin to whatever they want, the rest of the text is hard-coded into the ui.

It's the same text that shows if the instance is closed and invite requests are _not_ allowed:
<img width="497" alt="Screen Shot 2021-09-18 at 10 39 02 AM" src="https://user-images.githubusercontent.com/1807695/133897614-2f7d9185-685b-4c02-8663-50df8b7dd711.png">

When registration is allowed, there's no customizable text, just the registration form:
<img width="487" alt="Screen Shot 2021-09-18 at 10 39 55 AM" src="https://user-images.githubusercontent.com/1807695/133897651-748e28b0-ddeb-4c7e-bc29-78e404a463b5.png">

I think a good option here is to have separate customizable text for the invite flow and for when an instance is fully closed, and have the default text explain a little more about what happens when you fill out the form. It probably also makes sense to have a different header for the invite form - maybe "<Instance name> is invite-only" instead of saying it's closed.

**Comment by oragegu** [comment]
> I think a good option here is to have separate customizable text for the invite flow and for when an instance is fully closed, and have the default text explain a little more about what happens when you fill out the form. It probably also makes sense to have a different header for the invite form - maybe " is invite-only" instead of saying it's closed.

Customizable text sounds great!

**Comment by mouse-reeve** [comment]
<img width="487" alt="Screen Shot 2021-09-18 at 3 32 35 PM" src="https://user-images.githubusercontent.com/1807695/133910161-c3e55414-07d0-42c6-a011-c83e7e51bbd5.png">
(Text: "If your request is approved, you will receive an email with a registration link.")

Does this wording seem good to you? Instance admins will be able to customize it, but I'd like to get the default as clear as possible

**Comment by oragegu** [comment]
> Does this wording seem good to you? Instance admins will be able to customize it, but I'd like to get the default as clear as possible

Looks good to me!

**Comment by oragegu** [comment]
The customisable text works perfectly!

And is the dashboard new? It looks great!
