### ISSUE TITLE
/import form entry is too hard to find

### ISSUE THREAD

**Issue by Guanchishan** [bookwyrm-social/bookwyrm#1436]
**Is your feature request related to a problem? Please describe.**
`/import` entry is too hard to find.

I searched for the keyword "import" and after reading [the issues posted by others](https://github.com/bookwyrm-social/bookwyrm/issues?q=is%3Aissue+import), I realised that I needed to add `/import` to the url in the address bar to access the form.

**Describe the solution you'd like**
It would be helpful if there was an `/import` form entry in the sidebar of the settings page (like Mastodon).

**Describe alternatives you've considered**
N/A

**Additional context**
![image](https://user-images.githubusercontent.com/30859354/134041154-a883648c-72bd-4605-9ea4-f9f429037bd3.png)

**Comment by mouse-reeve** [comment]
Thank you! Currently, the import page is linked from the "Your books"/"你的书目" page:

<img width="1199" alt="Screen Shot 2021-09-20 at 11 38 08 AM" src="https://user-images.githubusercontent.com/1807695/134056285-37bb7e5f-7d9b-497d-8835-794c13d0edb5.png">
<img width="1191" alt="Screen Shot 2021-09-20 at 11 39 13 AM" src="https://user-images.githubusercontent.com/1807695/134056366-a99f52ac-24ad-47bd-88d4-9fdcda8bbc1a.png">

It was originally in the pulldown menu under your username at the top of the page, but since it's something that you need very infrequently (often only when you first join), I didn't think it made sense to keep it there.

Do you think it would have helped if there had been information about how to import in part of the onboarding flow you get when you first sign up? Another possibility is to show a link to the import page when you don't have any books on your shelves.

**Comment by Guanchishan** [comment]
So that's it! I apologize for not finding that￼.

> Do you think it would have helped if there had been information about how to import in part of the onboarding flow you get when you first sign up? Another possibility is to show a link to the import page when you don't have any books on your shelves.

I think both are good ideas. 

In addition, when registering, if the user does not choose to import immediately, the website can also tell the user where to find the entrance of /import later.

**Comment by mouse-reeve** [comment]
I resolved this with the PR but that doesn't mean we can't make different or additional changes to make this clearer -- but I'd rather get a new issue if there are further changes just to keep things moving. Thank you all!
