### ISSUE TITLE
Incorrect feed behavior with non-dockerized version

### ISSUE THREAD

**Issue by Flameborn** [bookwyrm-social/bookwyrm#1446]
This might be outside the project scope, as the official and supported installation method is via Docker, while I am hosting a non-Docker version. If this is indeed the case, feel free to close.

My Home/Books feeds do not seem to update properly. This happens whenever I start reading/finish a book, rate a book, etc. The state is reflected properly, e.g. a book is rated, or /added/removed from a shelf as expected.

The only exception is when I add a book on the book's page, there is no reading progress displayed, however, it appears when I refresh the book's page.

When I finish a book on the main feed page, a new reading progress is created, instead of the old one being updated. As such, I have a reading progress with just the start date defined, and a second one with the start/finish date.

I use Safari under MacOS, tried with version 14 and 15.

I also tried to use *manage.py* with the *populate_streams* command, but it does not seem to do the trick. My last status is from the 6th of September, when I started reading a book.

Debug mode does not seem to output any info, not even about invoking celery tasks, and the browser console displays no errors. Any help is greatly appreciated.

**Comment by mouse-reeve** [comment]
The problem you're seeing with read through dates being set incorrectly (creating new ones instead of using the in-progress dates) sounds like a separate issue from the rest, and unrelated to docker.

Just to make sure I'm understanding you correctly, when you create a status by interacting with a book, the status is created and shows up on the book's page and on your profile page, but doesn't show up your home or books timeline?

Based on the timing, it sounds like this might be related to the change to that updates the stream in celery. Do you have flower running, and if so are you able to see celery tasks related to updating the stream (for example, `add_status_task` or `populate_stream_task`)

**Comment by Flameborn** [comment]
> Just to make sure I'm understanding you correctly, when you create a status by interacting with a book, the status is created and shows up on the book's page and on your profile page, but doesn't show up your home or books timeline?
Correct.

> Based on the timing, it sounds like this might be related to the change to that updates the stream in celery. Do you have flower running, and if so are you able to see celery tasks related to updating the stream (for example, `add_status_task` or `populate_stream_task`)?

I don't see these running when I perform an action on the webpage, however, I see them listed when Celery runs, e.g. *bookwyrm.activitystreams.populate_stream_task*

Flower is running and listening on port 8888. The *FLOWER_PORT* environment variable is set as 8888.

Celerywyrm is modified to use *localhost* instead of *redis_broker* as its host, and it connects successfully according to the logs.

**Comment by mouse-reeve** [comment]
Okay, what sounds like to me is that the redis service that stores your timelines isn't getting updated by celery. Since it does sound like the tasks are being created in celery, and you have _some_ data in your timeline, that suggests to me that the problem is communication between the celery worker and the activitystreams redis instance. 

In flower, are you able to see and failed tasks related to activitystreams? If so, it should provide a stack trace, which would be a big help in figuring out what went wrong.

Another option would be to manually trigger a task like populate_stream without celery and see if it works synchronously or produces a helpful error state.

**Comment by Flameborn** [comment]
> Since it does sound like the tasks are being created in celery, and you have _some_ data in your timeline, that suggests to me that the problem is communication between the celery worker and the activitystreams redis instance.

I see lines in Celerywyrm, such as:

```
[2021-09-22 14:47:40,677: INFO/MainProcess] Connected to redis://localhost:6379/0
[2021-09-22 14:47:40,701: INFO/MainProcess] mingle: searching for neighbors
[2021-09-22 14:47:41,762: INFO/MainProcess] mingle: all alone
```

> In flower, are you able to see and failed tasks related to activitystreams?

Even when I run it with the *--debug* flag, I don't see any log output after it starts up. In the past, I used to see when it was executing tasks as I was performing various actions on Bookwyrm pages.

> Another option would be to manually trigger a task like populate_stream without celery and see if it works synchronously or produces a helpful error state.

I ran *manage.py populate_streams*, which returned in about a second with the following:

```
Populations streams dict_keys(['home', 'local', 'books'])
This may take a long time! Please be patient.
..................
```

**Comment by mouse-reeve** [comment]
Is the flower UI running when you visit it at port 8888? The logs for flower won't be helpful, but the UI itself should show you the state of tasks. 

Instead of using the `manage.py populatestreams` command, which creates a celery task, I want to see what happens if you call the task directly. In the python shell (`manage.py shell`):

```python
from bookwyrm import activitystreams, models
user = models.User.objects.get(localname="<your_localname>")
activitystreams.populate_stream_task("home", user.id)
```

The difference here is that `activitystreams.populate_stream_task` is called directly, instead of with delay: `activitystreams.populate_stream_task.delay`. Does running that produce an error? Does it fix your home stream? Do nothing?

**Comment by mouse-reeve** [comment]
Okay, that's consistent with my theory. First off, have you updated celery to use priority streams? This pr changes how celery is initialized, and if you don't have the queues that the app is expecting, tasks may be being sent into the void: https://github.com/bookwyrm-social/bookwyrm/pull/1376/files#diff-e45e45baeda1c1e73482975a664062aa56f20c03dd9d64a827aba57775bed0d3L66. 

If that doesn't fix it, I expect it's a problem with celery having access to your activitstreams redis, maybe a missing environment variable?

**Comment by Flameborn** [comment]
Spot on! For some reason, I didn't notice that the docker-compose command changed. After adding the -Q flag, I immediately started seeing tasks being queued/executed. As expected, now my feeds update properly.

I really shouldn't make it a habit of forgetting to check the simplest things. Time to close the oven door on my ears 😀

Thank you so much for bearing with me and of course for the solution!

**Comment by mouse-reeve** [comment]
No problem at all! I'm glad it had a simple fix ❤️
