### ISSUE TITLE
Already translated strings sometimes show up untranslated in UI

### ISSUE THREAD

**Issue by ghost** [bookwyrm-social/bookwyrm#1566]
**Describe the bug**
Some strings won't show up translated in the UI, showing the original English string instead. At times a string appears in the same page translated and untranslated. I can't see a pattern.

**To Reproduce**
1. Change language to Brazilian Portuguese
2. Check main timeline; some user's activities aren't translated; for instance: "*user* wants to read *book", "*user* started reading *book*", "*user* finished reading *book*". Others, like *user* commented" or "rated" or "reviewed" shows up properly. All these strings have been translated, but some won't show up in UI. Sometimes the same string appears in two different languages in the UI.

**Screenshots**
The same string in two different languages in the same page (language set to Brazilian Portuguese) (*user* finished reading *book*, *user* terminou de ler *book*):
![image](https://user-images.githubusercontent.com/15832384/138559990-247a746a-5344-4c3d-9d85-e6c13c67a2ca.png)
![image](https://user-images.githubusercontent.com/15832384/138559999-4c6849ef-5da5-46a9-aa7f-358405214162.png)

An already translated string that never shows up (*user* wants to read *book*, *user* quer ler *book*):
![image](https://user-images.githubusercontent.com/15832384/138560025-03207ebf-631e-4d28-9478-ce81b15482cd.png)

**Instance**
BookyWyrm.social

**Comment by hughrun** [comment]
Ok I think I have found the problem/solution:

In `views/reading.py` we check for `post-status` and `content`. If there is any `content` we pass the request through to `CreateStatus` with a `post-status` of "comment". 

But if there is no content - i.e. it's just changing the readthrough value of the book - then instead we pass it to `handle_reading_status` with a reference to the "shelf" (i.e. the intention).

```python
# post about it (if you want)
if request.POST.get("post-status"):
    # is it a comment?
    if request.POST.get("content"):
        return CreateStatus.as_view()(request, "comment")
    privacy = request.POST.get("privacy")
    handle_reading_status(request.user, desired_shelf, book, privacy)
```

This is where the problem begins, because `handle_reading_status` then creates a message based on the `shelf.identifier`:

```python
message = {
    "to-read": "wants to read",
    "reading": "started reading",
    "read": "finished reading",
}[shelf.identifier]
```
That message is then passed through as `content` to `create_generated_note` which dutifully creates a status _without a_ `reading_status`:
```python
status = models.GeneratedNote(user=user, content=content, privacy=privacy)
```
Because `get_header_template` can't find a `reading_status`, it defaults to using the `status_type` instead, which is `GeneratedNote`. Since `snippets/status/headers/generatednote.html` doesn't exist, it defaults to the `snippets/status/headers/note.html` template:

```python
try:
    header_type = status.reading_status.replace("-", "_")
    if not header_type:
        raise AttributeError()
except AttributeError:
    header_type = status.status_type.lower()
filename = f"snippets/status/headers/{header_type}.html"
header_template = select_template([filename, "snippets/status/headers/note.html"])
return header_template.render({"status": status})
```
And here in the `note` header, we simply pass through the untranslatable `content` which was originally created in `handle_reading_status`:
```django
{% if status.status_type == 'GeneratedNote' %}
{% with book=status.mention_books.first %}
{{ status.content|safe }} <a href="{{ book.local_path }}">{{ book|book_title }}</a>
{% endwith %}
```
So I guess either we need some way to make the `{{ status.content|safe }}` translatable, or we need to pass through the original shelf identifier and throw in some if/else statements based on that. Or maybe make a `generated_note` header template.

The latter might be the best option because then we could probably safely just do:
```django
{% with book=status.mention_books.first %}
{% translate status.content %} <a href="{{ book.local_path }}">{{ book|book_title }}</a>
{% endwith %}
```
