### ISSUE TITLE
date unpopulated when starting reading a book

### ISSUE THREAD

**Issue by jzacsh** [bookwyrm-social/bookwyrm#1582]
**Describe the bug**
> A clear and concise description of what the bug is.

moving a book to the default/auto-generated "currently reading" shelf doesn't populate a start date.

**To Reproduce**
1. Go to any book in your "to read" shelf
2. mark the book as currently reading, somehow[a]; eg:
    - 2.1) Click on "move book" drop-down under the book's description, choose "currently reading"
    - 2.2) _OR_ click on "start reading" button under the books cover art
3. Come back another day to your "currently reading" shelf, to use "update progress"
4. **Bug/unexpected**: notice the book seems to have undefined data for the start date

[a]: this choose-your-own-journey option for this step might be key to the bug being reproducible; I'm not sure which approach (or if both) causes the bug. I just know I keep seeing the end result of the bug (step 4). Screenshot attached of the two options for this step.

![Screenshot showing book on to-read list and the UI for marking it as currently reading](https://user-images.githubusercontent.com/156228/139560704-0c22a4e9-4043-46aa-8095-c1840e808d73.png)

**Expected behavior**
> A clear and concise description of what you expected to happen.

Step 4 should have revealed an already populated date value of the day that step 2 occurred.

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Instance**
> On which BookWyrm instance did you encounter this problem.

bookwyrm.social

**Additional context**
> Add any other context about the problem here.

I'm filing this as a bug because I could swear this used to work as I'm describing expected. But I could be wrong, in which case I'd say this maybe is a legitimate feature request.

---

**Smartphone (please complete the following information):**
    - Device: Google pixel 5
    - OS: Android 12
    - Browser: Google Chrome Beta
    - Version: `96.0.4664.27` _(that's browsers version.. if this prompt was meant to ask for the web version of Bookwyrm being served to me, then I'm not sure - I'm not seeing a tag anywhere in the footer of the UI or anything)_

**Comment by hughrun** [comment]
I noticed yesterday this also happens for _finishing_ reading books. In that case the same thing happens (the "finished date" isn't populated) and in addition, the books is not counted towards your reading goal.

**Comment by hughrun** [comment]
Basically the problem is that changing the shelf using the `shelf-selector` dropdown just triggers a self action, whereas using the shelve button triggers a modal and then a `ReadingStatus` update.

I have a possible solution for this, but @mouse-reeve we'll need you to comment on what the _intended_ approach for shelves is - there is an anomaly that may or may not be intentional. As a separate matter, if we did it this way there would also need to be some CSS normalisation in one direction or the other otherwise the buttons look a bit weird.

If we add a simple filter then if the `shelf.identifier` is a reading status shelf, we can swap in the shelve button instead of the shelf selector, like this:

![shelve_not_shelf_select](https://user-images.githubusercontent.com/17669239/141706501-70fdfb8d-dac9-45ff-ba9f-6c3138617a75.png)

Note progress is updated:

![with_shelved_dates](https://user-images.githubusercontent.com/17669239/141706509-6256bc38-e881-4b6d-8e31-458039ff7c6c.png)

This is much simpler as a solution than anything else I can think of.

However, as you may have noticed from these example screenshots, it's possible to have a book on two shelves simultaneously. This is for much the same reason as this bug exists: the `shelve_button` triggers. There's a comment in `views/shelf/shelf_actions.py` that suggests being able to be on multiple shelves as long as only one of them is a read status shelf is the intended behaviour, I just want to be sure that's still the case, otherwise this might just be complicating things.

**Comment by mouse-reeve** [comment]
oooh that explains this! This design was originally intentional, when the concept of how reading status updates were generated was fuzzier, but I think it makes sense to use the shelve button across the board. 

And yes, you should be able to have a book on a custom shelf and a reading status shelf, but not on two reading status shelves at the same time.

**Comment by mouse-reeve** [comment]
Thank you, that button has been bugging me for ages! I'd say add the `is-small` class to the big one
