### ISSUE TITLE
bookwyrm also for music albums/CDs ??

### ISSUE THREAD

**Issue by rocky-III** [bookwyrm-social/bookwyrm#1588]
it would be really interesting to have something link bookwyrm also for  music albums/CDs

Could you imagine to integrate this into the software? 

Instead of  https://openlibrary.org/ one could use e.g. https://musicbrainz.org/ to get the basic infos about music albums/CDs

**Comment by mouse-reeve** [comment]
I totally get the appeal here! Unfortunately from a logistical standpoint, this isn't on my roadmap. I'm trying to keep bookwyrm's scope in check, and managing the complexity of book data is already so much a challenge that adding in other media is an overwhelming challenge for the size and development energy of this project. I'm going to convert this to a discussion since it isn't something I have the capacity to act on, but I appreciate the interest in expanding the conceptual model of managing media metadata and social activity around it to other things besides books.
