### ISSUE TITLE
Books on multiple shelves duplicated in the "all books" view

### ISSUE THREAD

**Issue by mouse-reeve** [bookwyrm-social/bookwyrm#1643]
<img width="1172" alt="Screen Shot 2021-12-02 at 11 47 40 AM" src="https://user-images.githubusercontent.com/1807695/144495864-f94425a7-b11f-4df4-8ab7-c850d5a17996.png">

**Comment by hughrun** [comment]
Is this happening because `shelve_button` isn't removing old reading status `ShelfBook` objects when the user "moves" the book?

**Comment by mouse-reeve** [comment]
Hm, I don't think so? The book duplication seems to be happening because the query treats each shelf's version of the book as unique. I'm not sure about the duplicate "remove" buttons but I suspect adding a `distinct()` to a query would help with them.

**Comment by hughrun** [comment]
Ok I have worked out what's causing this, though I don't know how to fix it and I think there may be two bugs here.

The first bug is what I was referring to earlier: notice that `Remove from Currently Reading` appears twice, which it shouldn't. I haven't looked into that more yet.

The second bug is that each edition appears once for every shelf it is on, in the "All Books" view. I'm pretty sure this is happening because when the book is annotated, we collect the `ShelfBook.shelf_date`:

in views/shelf.py:
```python
books = books.annotate(
    rating=Subquery(reviews.values("rating")[:1]),
    shelved_date=F("shelfbook__shelved_date"),
    start_date=Subquery(reading.values("start_date")[:1]),
    finish_date=Subquery(reading.values("finish_date")[:1]),
    author=Subquery(
        models.Book.objects.filter(id=OuterRef("id")).values("authors__name")[
            :1
        ]
    ),
).prefetch_related("authors")
```

If I comment out that line, we don't get duplicates, but we also can't sort by shelved date. What we ideally want is some way to remove `shelved_date` from the "all books" view OR perhaps better would be to somehow annotate it in a way that whatever is the _latest_ shelved date is used for the All Books view and we don't have duplicates.

Unfortunately, I'm a bit stumped as to how we can do either of those. Any ideas?

**Comment by hughrun** [comment]
LOL I just figured out what is causing the multiple remove buttons from here #1693 . It's listing EVERY shelf the books is connected to via a ShelfBook: across the whole database, not just for the logged in user!!! Whoops:

In `shelf_selector.html`:
```
{% if shelved_in in book.shelves.all %}
```

@mouse-reeve should I create a separate PR for that, or is there some way for me to add to #1740?

**Comment by mouse-reeve** [comment]
😂 heck, that's so easy to miss and explains so much
