### ISSUE TITLE
deal with requests for /@username

### ISSUE THREAD

**Issue by binyamin** [bookwyrm-social/bookwyrm#1685]
### Problem
Mastodon puts public accounts at `example.org/@username`. People might expect bookwyrm to do the same.

### Solution
Redirect `/@mouse` to `/user/mouse`. With regards to code, this sounds pretty easy. Keep in mind that this uses up any URL path starting with "@".

### Other Stuff
Come to think of it, why _is_ the user profile at `/user/mouse`? The at-symbol ("@")  is rarely used in URL paths otherwise. It's a nifty way of shortening the URL while keeping other URL paths safe.

**Comment by binyamin** [comment]
@hughrun I guess my writing was too condensed; I agree with everything you wrote. It would be silly to copy Mastodon's style, for the sake of it.

My main concern is that users may _expect_ `/@mouse` to work[^1]. In terms of UX, it's important that a user completes their goal (eg. ["Great Design is Invisible"](http://bokardo.com/principles-of-user-interface-design/#great-design-is-invisible)). Of course, you've got to make sure this doesn't interfere with some other aspect, but I don't see that happening here.

[^1]: Case in point, Mastodon, Pixelfed, and write.as each play it safe, and serve or redirect requests for `/@binyamin`.

**Comment by hughrun** [comment]
Yep that's totally valid. 

I guess my concern is that every time other fediverse apps do something to match what Mastodon has chosen to do in the name of "reducing user friction", it reinforces the soft power of the core Mastodon devs in directing standards because of their sheer weight of users. They've made some good decisions (like remote following using the ostatus subscribe protocol) but also some dubious ones. 

I feel like `/user/{name}` is a pretty intuitive place for a user profile to be, but unless @mouse-reeve knows of some potential or existing problem it would cause, allowing for both patterns isn't intrinsically bad.

**Comment by mouse-reeve** [comment]
I think it would be super straightforward to add /@username paths, should just be a matter of adding another line to urls.py
