### ISSUE TITLE
Let users create groups

### ISSUE THREAD

**Issue by mouse-reeve** [bookwyrm-social/bookwyrm#170]
Idea: A user can create a public or private/invite-only group of other users and post content only to that group. Content posted to the group would show up in the feeds of group members, and in the group's dedicated page.

Use cases:
 - a book club or group read
 - a small circle of friends who want to share content privately with each other
 - a public reading challenge (like, read a book a week, or whatever)
 - a public interest group that wants to curate their content in one place or have less visibility by not showing up in the public feed

**Comment by loganmhb** [comment]
I would be interested in working on this if you are looking for help! (I'm particularly interested in the private-book-club version, but it makes sense to design them together probably.)

**Comment by rkingett** [comment]
I'm interested in this as well.

**Comment by mouse-reeve** [comment]
definitely looking for help on this, go for it :)

**Comment by loganmhb** [comment]
I'm reading up on ActivityPub to try to get a sense of how this would work -- sketching out some ideas here to see if they make sense.

I see that there is an ActivityPub "Group" actor type which it probably makes sense to use for this. Then activities which are conducted in the context of a group (which could be any type of activity I think? review, comment, reading update, etc -- though there are plenty of questions about how the UI for this should work) can be directed to the group's members via a `members` collection.

(Or maybe it makes sense to simply use the standard-defined `followers` collection, at least for public groups?)

So a reading update in the context of a group could look something like this:
```
{
  '@context': 'https://www.w3.org/ns/activitystreams',
  'id': 'https://your.domain.here/user/logan/status/3/activity',
  'type': 'Create', 'actor': 'https://your.domain.here/user/logan',
  'published': '2020-06-18T13:18:50.288697+00:00',
  'to': ['https://your.domain.here/groups/my_private_bookclub/members'],
  'object': {
    ...
  }
}
```

(I am not sure how verifying group membership in order to access content would work across federated instances. I suppose when a user requests a post that is private to a group it would be necessary to ask the server on which the group exists if they are a member, or something along those lines?)

I think this data model would support use cases like "mark this book as read, tell my followers, and also publish it to this group I'm in", though I'm not sure how you would make this work smoothly in the UI -- it would probably be clunky to ask for a context every time a user creates an activity.

**Comment by mouse-reeve** [comment]
this all sounds right to me (especially the part about the UI being challenging). I think you're running into a lot of the same questions around post privacy, which hasn't been implemented yet -- "post to group" is, I think, essentially in the same list of options as "public" and "followers only"

every request to view a post (which can happen on the timeline or in the standalone page) should have to be checked for whether the requester is authorized to view it, which I *think* is roughly:
 - is the post/group public
 - is the post followers-only and is does requester follower the poster
 - is the group private and is the requester in the group

**Comment by loganmhb** [comment]
That makes sense. It sounds like there are probably two ways to approach this:
- start by implementing groups whose posts are always public (but membership not necessarily open)
- start by implementing post privacy

Then you could combine the two hopefully without too much friction to get groups with private posts.

Regarding the UI complexity, it also seems sort of likely to me that it would be possible to start out by implementing the data- and protocol-level support for groups with an awkward or limited UI (e.g. you have to go to the groups page and make a comment/review from there, or something) and then improve the UI down the line.

**Comment by mouse-reeve** [comment]
Agreed! I don't think post privacy or the UI need to be solved to implement groups at this point, just something to keep in mind :)

**Comment by jaschaurbach** [comment]
Can this be closed?

**Comment by mouse-reeve** [comment]
Yes, there's plenty more work available on this but I think we can part with a very old issue about it
