### ISSUE TITLE
Backups aren't being automatically pruned

### ISSUE THREAD

**Issue by mouse-reeve** [bookwyrm-social/bookwyrm#1718]
Backups are being saved correctly, but they aren't being pruned.

(tagging @bcj in case it's something obvious)

**Comment by cincodenada** [comment]
It looks like the pruning cron is disabled by default - just checking, did you uncomment the weeding cron in `postgres-docker/crons`?

**Comment by mouse-reeve** [comment]
yes, I enabled it - but wise to double check!

**Comment by cincodenada** [comment]
I was actually looking at this earlier and I don't want to knock the existing solution too much - it certainly seems solid and well-thought-out - but fundamentally, trying to run two processes (cron and postgres) in one Docker container is always gonna lead to fighting the system a bit, since Docker is pretty aggressively built around one process (and its child processes, of course!) per container. The current solution accomplishes that with it's awk hacking of the arguments and such, but to some degree it feels like it's adeptly fighting a battle that doesn't need to be fought.

The other thing about the current solution that makes me a little worried is that the backups are still in a docker volume that's attached to the db server, so it won't protect you from, say, accidentally blowing away the database container and its volumes, which I have certainly done before :see_no_evil: Generally, keeping your backups as far away from the database server as practical is wise!

I've been poking at integrating a separate container like https://github.com/prodrigestivill/docker-postgres-backup-local alongside the db container as an alternate solution - it already uses most of the same variables Postgres uses, and backs them up to a local directory on the host machine. Linked from that README is a similar project it's based on that does the same, but to S3. I've been toying with offering one or both of these as backup options in Bookwyrm somehow, but I'd be interested in thoughts from @mouse-reeve and/or @bcj on that!

**Comment by mouse-reeve** [comment]
I think that's a good idea, and backing up to the host machine (or an s3 bucket... #1296 ) would be an improvement in robustness

**Comment by mouse-reeve** [comment]
Backups ARE being automatically pruned
