### ISSUE TITLE
Author pages with no bio look odd

### ISSUE THREAD

**Issue by mouse-reeve** [bookwyrm-social/bookwyrm#1814]
Just a big empty space!
<img width="1280" alt="Screen Shot 2022-01-11 at 7 01 02 PM" src="https://user-images.githubusercontent.com/1807695/149056956-b1dfad5c-5c42-42a4-aa5f-5894ef01a982.png">

**Comment by pramod74** [comment]
Hi @mouse-reeve ,

I would like to work on this issue. Can you please guide me on what needs to be done?

Thanks,
Pramod

**Comment by AnasGamal** [comment]
Hello, @pramod74 @mouse-reeve 

I would like to work on the issue but I am not able to find time right now, however I looked at the templates and I think that file needed to be edited for this issue to be solved is /bookwyrm/templates/author/author.html, which is the author profile html template.

**Solution(1)**: There should be one div row, containing 2 columns, the left column will contain: author bio section, other books by author section. the right column will contain: Author details section and external links sections.

However, I suggest a simple rearrangement: author bio and other author details (bio and external links) should be in one column on the left, the column on the right contain only "other books by author" section.

@pramod74 Essentially, you should apply Solution(1).
Later, if @mouse-reeve wants to, he can apply my suggestion later easily or I can do it if he agrees.

**Comment by mouse-reeve** [comment]
I think that sounds like a good solution!

**Comment by ashwani3011** [comment]
Hello is it done

**Comment by mouse-reeve** [comment]
> Hello is it done

Wonderful! Can you open a pull request against this repository? (https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request)

Once you do that, I will test it out, let you know if anything needs tweaking, and then get it merged.

**Comment by pramod74** [comment]
Hi @ashwani3011,

Am on the job. Will submit a PR shortly.

Thanks,
Pramod

**Comment by mouse-reeve** [comment]
Ah sorry I misread the previous post. Thank you for your work @pramod74, and take all the time you need. I look forward to the PR :)

**Comment by pramod74** [comment]
Hi @mouse-reeve,

Thanks for your encouraging words but I am sorry, I did not pay attention earlier to the fact that the project is coded mostly in Python. I am good at basic HTML/CSS but have not really worked on Python/Django earlier and am finding it challenging to implement a solution to the issue. Request you to assign this issue to someone else. Sorry again.

Thanks,
Pramod

**Comment by mouse-reeve** [comment]
> Hi @mouse-reeve,
> 
> Thanks for your encouraging words but I am sorry, I did not pay attention earlier to the fact that the project is coded mostly in Python. I am good at basic HTML/CSS but have not really worked on Python/Django earlier and am finding it challenging to implement a solution to the issue. Request you to assign this issue to someone else. Sorry again.
> 
> Thanks, Pramod

No problem at all, thanks for letting me know

**Comment by AnasGamal** [comment]
> Hi @mouse-reeve,
> 
> 
> 
> Thanks for your encouraging words but I am sorry, I did not pay attention earlier to the fact that the project is coded mostly in Python. I am good at basic HTML/CSS but have not really worked on Python/Django earlier and am finding it challenging to implement a solution to the issue. Request you to assign this issue to someone else. Sorry again.
> 
> 
> 
> Thanks,
> 
> Pramod


Hello Pramod,

I don't know Python either, but I believe that you can do this without knowledge of python, let us look at an example of the file mentioned above:
```

    {% if author.bio %}
    <div class="column">
        {% include "snippets/trimmed_text.html" with full=author.bio trim_length=200 %}
    </div>
    {% endif %}

```

Notice those two statements `{% if author.bio %}` and `{% endif %}`.
I believe that the first statement begins an if statement which basically means "if there is an author bio, then.." after that comes a basic div element with the content we need to display author bio, so basically it is saying "if there is an author bio, display this div" and the `{% endif %}` just ends the statement.
I think you can treat the code beginning from `{% if author.bio %}` to `{% endif %}` as if it represents the whole div element.
So what is different than a normal html page is that if you are going to move the div element for some reason you will just need to copy those statements along because they represent the case in which the div element should appear.
Other than that I think you will do what you are going to do with a basic HTML page, play with css classes for the div element to get the right column and row structure and move div elements (with their if statements, as we established) around.

Again, I don't know python so I apologize if I said anything wrong I am just trying to make it easier and help, @mouse-reeve please correct me if something is wrong or if my whole answer is wrong.

I hope that this might help and I encourage @pramod74 to try what I explained if he still want to work on that issue.

**Comment by pramod74** [comment]
Thanks @AnasGamal for your helpful suggestions. It really made sense to me. Unfortunately, I was not able to use them this time. Hopefully, should be able to help with some other UI related issue going forward, as and when required.

@mouse-reeve This is really an elegant solution. Wonderful!
