### ISSUE TITLE
Feature request: allow multiple people to add to a shelf

### ISSUE THREAD

**Issue by voltagex** [bookwyrm-social/bookwyrm#1827]
**Is your feature request related to a problem? Please describe.**
I'd like to collaborate with multiple people to build a reading list. 

**Describe the solution you'd like**
Allow contributor access to a shelf.

**Describe alternatives you've considered**
Shared Google Doc/Etherpad etc

**Comment by mouse-reeve** [comment]
You can do this with lists! With a list, you can set the curation type to let anyone add books, have the list owner approve submissions, or have a group of people who can add to the list. You can find lists at /list

**Comment by voltagex** [comment]
Oops! Sorry @mouse-reeve, I did look for this, but I will admit I didn't look very hard.

**Comment by voltagex** [comment]
I am missing some info here, how can people request to be added to a group?

**Comment by mouse-reeve** [comment]
If you've already created the group, you can click through to the group's page from the list:
<img width="1188" alt="Screen Shot 2022-01-16 at 5 33 58 PM" src="https://user-images.githubusercontent.com/1807695/149687743-27eaf2a5-390e-4fe2-ae8b-1bd771150fcf.png">

Can you see all your groups from your user page, at the url `/user/<your username>/groups`. From there you can create and view your groups.

On the group page, there's a search box where you can enter a username -- it will find the user and let you add them to the group. For the time being, groups can only be people who are on the same server.

**Comment by hughrun** [comment]
@voltagex Due to some complexities of how the underlying BookWyrm structure works, you need to create a **group** before you can create a group-curated list. If you don't have any groups, the "Create list" form will invite you to do so when you select 'group' as the list curation type. Or alternatively go to your profile page and select the 'Groups' tab. Once you have created a group you can also just create a list from the group's page which will be at `/group/{group_id_number}`.

You add group members from the group page:
![Screen Shot 2022-01-17 at 5 47 39 pm](https://user-images.githubusercontent.com/17669239/149720935-9e668ced-ff5d-402b-a6ba-ab81cfa5a5fc.png)

If this is confusing and you are able to describe a way that would be less confusing, please let us know!

**Comment by voltagex** [comment]
Thanks Hugh, Mouse.

I should probably close this issue and open another one, I think this issue is solved.

**Comment by mouse-reeve** [comment]
Thanks!
