### ISSUE TITLE
Django pickled model version mismatch 

### ISSUE THREAD

**Issue by nycterent** [bookwyrm-social/bookwyrm#1903]
**Describe the bug**

Getting a warning:

web_1             | /usr/local/lib/python3.9/site-packages/django_redis/serializers/pickle.py:32: RuntimeWarning: Pickled model instance's Django version 3.2.10 does not match the current version 3.2.11.

As a workaround flushing Redis activity instance works - the warning is gone

**Comment by mouse-reeve** [comment]
I believe this was caused because the Django version was updated in #1884, which means that some of the cached data was made relative to an earlier Django version. For other folks who run into this, if the warning shows up but the site still runs, it's probably easier to leave it than flush the cache. If you do need to flush the cache, you'll need to run `./bw-dev populate_streams` and `./bw-dev populate_suggestions` afterwards.

**Comment by mouse-reeve** [comment]
I've replicated this locally and I don't think it's a problem we have to fix (at least at this point). The warning will clear on its own when the various caches are updated, and there isn't a compatibility problem between the versions of Django. But it's a good thing to keep in mind for future library updates, so thank you for flagging!
