### ISSUE TITLE
Updates to remote accounts aren't reflected

### ISSUE THREAD

**Issue by Tak** [bookwyrm-social/bookwyrm#2021]
**Describe the bug**
Updates to remote accounts aren't reflected.
For example, [V](https://social.scribblers.club/@vicorva) recently changed their display name and avatar. However, these changes aren't visible in their subsequent [replies](https://reading.taks.garden/user/vicorva@social.scribblers.club/status/2726) or [local profile](https://reading.taks.garden/user/vicorva@social.scribblers.club).

**To Reproduce**
1. Interact with a mastodon user from bookwyrm
2. Update the mastodon user's display name
3. Interact with the bookwyrm user again from mastodon

**Expected behavior**
Updates to displayed information from the mastodon account are propagated to the bookwyrm instance

**Actual behavior**
Updates to displayed information from the mastodon account are not propagated to the bookwyrm instance

**Instance**
reading.taks.garden

I can't *swear* this isn't a duplicate of https://github.com/bookwyrm-social/bookwyrm/issues/1553

**Comment by mouse-reeve** [comment]
It's a separate issue from 1553. 

What _should_ happen is that when a user updates their profile, an `Update` activity is sent to the remote instances, and then the remote instances update their record of that user. There are a number of reasons this might not happen:
 1. The home instance doesn't successfully send out the update
 2. The home instance sends out the update but not to the remote instance in question
 3. The remote instance is temporary unavailable and doesn't receive the update
 4. The remote instance rejects the update because of an authentication issue
 5. The remote instance recieves the update but has an error updating the user record

I think the 4th reason is the most likely, since we've been seeing other federation issues around authentication, and I haven't seen any errors relating to updating remote users in Sentry. If you can check flower (it runs on port 8888), you should be able to find the task that updates the user, if it was recieved and authenticated. If there was an error, it would be found there too. I think these are also in the celery_worker logs.

**Comment by Tak** [comment]
It looks like I've updated my instance since then, so there's nothing left in the logs. :neutral_face:

**Comment by Tak** [comment]
It seems to have updated sometime in the last two weeks (maybe they updated their profile again and the update on my side succeded this time?) - should I close this?

**Comment by WesleyAC** [comment]
Going to go ahead and close this, glad it got resolved :)
