### ISSUE TITLE
CSS fails in bookwyrm.social

### ISSUE THREAD

**Issue by jartigag** [bookwyrm-social/bookwyrm#2099]
Hi, not sure if this is the best place to report this, but I saw [this screenshot in the fediverse](https://mastodon.social/@editora/108239845200923021) and I thought it could be some issue loading the CSS stylesheet:

https://bookwyrm-social.sfo3.digitaloceanspaces.com/static/css/themes/bookwyrm-light.css

**To Reproduce**
1. Go to https://bookwyrm.social/
2. This stylesheet [bookwyrm-light.css](https://bookwyrm-social.sfo3.digitaloceanspaces.com/static/css/themes/bookwyrm-light.css) can't be loaded.

**Instance**
BookWyrm.social

**Additional context**
I think there's a problem with the SSL certificate, because connection can't be established on port 443.

**Comment by mouse-reeve** [comment]
I know this has been happening, as far as I know just on b.s during high load. I think it's a timeout/connection issue rather than an actual ssl or code problem

**Comment by 0xMiya** [comment]
I have this same problem since a 2 or 3 days. It's only happening on one of my devices. All other devices load just fine. So it seems unlikely to me to be caused by high server load.

Only the request to GET "/" is successful, all other requests fail to connect.

I tested it in both, Firefox and also a clean install of Librewolf (ver. 100.0 on Arch Linux) with the same result.
Is it possible that it has something to do with the Browser/User Agent used?
