### ISSUE TITLE
Recent activity of followed accounts not appearing on home or discovery feeds

### ISSUE THREAD

**Issue by stopregionblocking** [bookwyrm-social/bookwyrm#2107]
Have never had an issue with this before. It appears to have begun sometime in the last 3 days. Couldn't locate any changed user settings that might be responsible.

**Comment by mouse-reeve** [comment]
I would guess that this is a queuing delay, since I haven't pushed any code changes in a while. What instance is this on?

**Comment by quaayd** [comment]
This has been happening to me. Some posts i did yesterday only showed up in my feed this afternoon. some that i did earlier today have not made it to the home page. They are appearing in my user profile page. the latest post

bookwyrm.social, running on the latest version of firefox on macos 12.3.1, also same issue on chrome.

**Comment by stopregionblocking** [comment]
> I would guess that this is a queuing delay, since I haven't pushed any code changes in a while. What instance is this on?

The main instance, bookwyrm.social.

**Comment by mouse-reeve** [comment]
b.s is having repeated issues where, when a large import is started, the high priority queue that handles updating the timelines gets backlogged, which causes this kind of behavior. There isn't a simple bug fix here, unfortunately, but I think there are a few angles here:

1. It seems like tasks that are not high priority are ending up in the high priority queue, so that needs investigation
2. There may be a way to simply reduce the number of tasks overall by reviewing the code for efficiency problems
3. There could be better celery configurations that would prevent these kinds of backlogs
