### ISSUE TITLE
Choose which name to show for author of book if author has several names

### ISSUE THREAD

**Issue by jaschaurbach** [bookwyrm-social/bookwyrm#2371]
**Is your feature request related to a problem? Please describe.**
Autors may change names because they marry or because they just want to do it (like I did). A book shows only the "main" name as author. Example: https://books.jascha.wtf/book/534/s/neustart - the book is written by me, Jascha Ezra Urbach, before I changed my name from Stephan Urbach. The author page https://books.jascha.wtf/author/110/s/jascha-ezra-urbach shows that the name exists in the database. I want to be able to show the old name but when I klick the link I get to the correct author page but with a note that you are forwarded from $oldaname. 

**Describe the solution you'd like**
If an author of a book has several names and they are connected give the possibility to chose which name should be shown for the book via drop down menu. 

**Describe alternatives you've considered**
Create another author and have separate datasets which only leads to fragmentation.

**Additional context**

**Comment by mouse-reeve** [comment]
If you change the name when editing the author, the URL will still work -- the names in the url are not actually used for resolving the link, and are corrected to the name that is provided in the author description. For example, you can still get to your author page by clicking https://books.jascha.wtf/author/110/s/hello (or any other random text, or nothing there at all).

**Comment by jaschaurbach** [comment]
Ah, okay. 

But there is still the other issue that there are several books by the same author with different names and no way to say which oil the known names should be displayed

**Comment by jaschaurbach** [comment]
The field is ordered but what me bothers it that there is a cover with OLDNAME on it while there is ANOTHERNAME written after the title. I would Leo to set which name could be shown there _if_ the name belongs to the author.

**Comment by mouse-reeve** [comment]
Is your preference to have the author name display differently based on what author name is used on the book cover?

There are a couple reasons I haven't done this. From a technical perspective, it's just a lot of work to display the author's name conditionally like that. And I'd be reluctant to use an old name for someone, even if it's the one on the cover of a book, since it may be a deadname or just a name that the person doesn't want advertised for whatever reason. Using the "canonical" name for the author across the board seems like the best practice in order to have people's most correct names shown, and there being some potential confusion to the user if a worthwhile cost to me.

**Comment by jaschaurbach** [comment]
this is no hill I am willing to die on. 

I would prefer to see my deadname by this Books (or: Editions of a book) like it is on the cover than showing my name because like this I had people ask why there is another name and I had more talking than I would otherwise but that is only my experience.

I will close this then :)
