### ISSUE TITLE
Generic CSV import

### ISSUE THREAD

**Issue by marcusyoung** [bookwyrm-social/bookwyrm#2411]
In addition to the import from other platforms, I would like a generic CSV import option. Yes, you can use a none exported CSV file of your own, but this would make it clearer to users that they can import their own CSV file (e.g. from a database they may be keeping at home). In addition, documentation would advise on the required structure of this CSV file.

**Comment by mouse-reeve** [comment]
When I refactored the import system, I set it up so that each import can have an arbitrary mapping between CSV headers and imported user data fields. So in theory, a user might be able to preview a couple rows of their CSV file, get the system's best guess for how to map the data, and, as desired, manually select the metadata (like date read) that corresponds to that column. 

The remaining work is to create the UI for previewing the file and selecting the mappings, and save that to the `mappings` field on the `ImportJob` model object. From there, it's already equipped to import based on the mappings saved for the job.

**Comment by robsonsobral** [comment]
@mouse-reeve , until we have a super-duper-importer, could we have the list of available headers so we can manipulate the imported file ourselves? I want to import books to a custom shelf for **owned books**.

Thank you!

**Comment by marcusyoung** [comment]
You will need a column called shelf with value owned-books I should think.

**Comment by mouse-reeve** [comment]
At the moment, importing to custom shelves isn't supported
