### ISSUE TITLE
Cover images when placing a bookwyrm url into a mastodon post

### ISSUE THREAD

**Issue by iamjmulligan** [bookwyrm-social/bookwyrm#2565]
I don't know if this is a bug or its a feature thats needed but I'd notice when posting to mastodon and including the bookwyrm URL for the book  I am discussing that rather than embedding a book cover image it just includes a giant bookwyrm advert. I'd certainly prefer it to embed a cover image.

**Comment by mouse-reeve** [comment]
I believe that when a preview image is not available for a book, the template defaults back to the instance logo, which I'm guessing is what you mean by an advert. It would be a quick fix to use a book cover as a fallback on the book page for books with no generated preview image.

**Comment by iamjmulligan** [comment]
I mean like this.

![SCR-20230103-fgc](https://user-images.githubusercontent.com/7078397/210286298-d3dcc3a7-4176-45c8-a3fc-aed9a1ee9308.jpeg)

The bookwyrm page does have a cover image, and its one that appears in my feed, just that when I post the link to the book in mastodon for some reason its not displayed.

**Comment by mouse-reeve** [comment]
Yes, I see what you mean. Right now this is what it's doing:
1. if there's a book preview image, use that
2. if there's an instance preview image (that's what's in your screen shot), use that
3. otherwise use the instance logo

Instead, it should do:
1. if there's a book preview image, use that
2. **if there's a book cover, use that**
3. if there's an instance preview image (that's what's in your screen shot), use that
4. otherwise use the instance logo
