### ISSUE TITLE
Don't show a generic 413 server error upon submitting incompatible content

### ISSUE THREAD

**Issue by jan-eckhoff** [bookwyrm-social/bookwyrm#2633]
**Is your feature request related to a problem? Please describe.**
I added a new book to the database, filled out all the DB fields and uploaded an image that happened to be too big. Submitting led to a white 413 Content too large error page from the web server, so I didn't know what the problem was (could also have been a description text that was too long, or the ISBN field doesn't accept the hyphens I added, or...)

**Describe the solution you'd like**
If there's something wrong with the content I add, I'd like the system to tell me right away, i.e. on the same page at the field that contains the error. Failing that, I'd still like the system to tell me what went wrong upon submitting, i.e. instead of showing me a generic 413 server error, tell me what part of the content was wrong and how I should fix it.

**Describe alternatives you've considered**
the only alternative I saw was an educated guess

**Additional context**
See [this rant](https://chaos.social/@janeckhoff/109767477467168537) for more context.

**Comment by hughrun** [comment]
It sounds like this is a [`SuspiciousOperation`](https://docs.djangoproject.com/en/3.2/ref/exceptions/#django.core.exceptions.SuspiciousOperation) `(RequestDataTooBig)` error, but I'm struggling to replicate the bug, even using an absurdly large image file. I wonder if something changed with image file handling since this issue was reported.
