### ISSUE TITLE
Make "Position: On page" a freeform field

### ISSUE THREAD

**Issue by WesleyAC** [bookwyrm-social/bookwyrm#2640]
I want to include a quote from a book that appears in the preface, with a page number like "ix". However, the "Position" indicator doesn't allow non-numeric values :(

I think that the "Position" (at least, the "On page" version) should allow freeform text input, both to allow for roman numerals commonly seen in prefaces, and for more idiosyncratic page-numbering schemes.

(See, for example, [this quote](https://bookwyrm.social/user/wesleyac/quotation/918586#anchor-918586))

**Comment by mirrorwitch** [comment]
More motivation for this is anything scholarly:

 - scholars will write pages like "32r" or "32v" when quoting from manuscript positions, to indicate which side of the folio it is, recto or verso (because manuscripts can be hard to decipher and this helps the citation-seeker to locate the relevant passage).
 -  scholars will write addenda like "32 n.5" (with varying syntax) to say "footnote 5 on page 32", for the same reasons (especially in cases where, for example, the footnotes are comments by a translator or editor about an original text by a different author, so citing "p. 32 n5" means a different person than citing "p. 32").
