### ISSUE TITLE
Adding new book fails 'quietly'

### ISSUE THREAD

**Issue by thom-github** [bookwyrm-social/bookwyrm#2651]
**Describe the bug**
I'm trying to add a new book on bookwyrm.social. After filling in the relevant parts of the form, I click 'Save'. The page reloads, but no book gets added. I'm still in the form, 'Author' is empty, everything else stays the same. No error message of any kind.

**To Reproduce**
I go to https://bookwyrm.social/create-book
I add Title, Subtitle, Language, Publisher, First published date (Year only), Published Date (Year only), URL for Cover image, Format, Pages, ISBN 13. I leave everything else blank.
I click on 'Save'
Browser loads something, page reloads, still on the same form. Author field is now empty, everything else is still there. No book gets added. No error message that I can see.

**Expected behavior**
Well..... either the book gets added, or the user somehow gets informed, what part of his input is blocking the book from getting added :)

**Instance**
bookwyrm.social

---

**Desktop (please complete the following information):**
    - OS:: MX Linux
    - Browser: I tried both Firefox (109) and Chromium (109.0.5414.119)

**Comment by chdorner** [comment]
Just tried running through the steps to reproduce this:
> I add Title, Subtitle, Language, Publisher, First published date (Year only), Published Date (Year only), URL for Cover image, Format, Pages, ISBN 13. I leave everything else blank.

and I get form validation errors with the two publishing dates:
<img width="652" alt="image" src="https://user-images.githubusercontent.com/112063/216764494-6fa7d523-25b2-4457-aeae-b87ff221c214.png">

Do you not see those errors? Or is it maybe not obvious because the form loads again but without any generic error message near the top and the validation errors for specific fields in this case require a user to scroll further down to see them?

**Comment by thom-github** [comment]
You're right, THAT was the issue. And no, I hadn't noticed those warning messages.
I suppose it would be a feature request to make those messages white-on-red instead? :)

Thank you very much.

**Comment by mouse-reeve** [comment]
It might be good to have a red notification banner at the top of the form when there are inline errors, since it's easy to miss them
