### ISSUE TITLE
The cover images in statuses viewed via Mastodon are too big

### ISSUE THREAD

**Issue by bpeel** [bookwyrm-social/bookwyrm#2835]
**Describe the bug**

When you view a status from BookWyrm in Mastodon it looks like this:

![image](https://user-images.githubusercontent.com/12873/234202537-a11b7943-7509-4e98-8691-4258d24b991b.png)

The cover image is huge and gets cropped so you can only see a small part of it. BookWyrm can generate quite a lot of statuses, for example usually when someone finishes reading a book they will mark it as finished and then write a review and this ends up as two statuses. The huge images can make the timeline look cluttered.

**Expected behavior**

I’m not sure if this is possible, but it would be nice if the cover image was really tiny like you get for the preview when you send a link on Mastodon:

![image](https://user-images.githubusercontent.com/12873/234203608-9c90a787-db8a-4191-b0e9-5a28b4f0cd05.png)

**Comment by mouse-reeve** [comment]
Your instance can generate preview cards which will be used instead of book covers and will display nicely on other social media platforms. For example:
<img width="582" alt="Screen Shot 2023-04-25 at 2 06 50 PM" src="https://user-images.githubusercontent.com/1807695/234404117-3c8c1953-0396-4da1-bf21-f1119a41a0ed.png">

It may be that your instance doesn't have these enabled, or the preview image hasn't been generated for that book yet.

**Comment by bpeel** [comment]
Thanks for the feedback, I didn’t know about that option. Yes, I haven’t enabled it on my instance yet, so that explains the problem. To be honest it looks like the preview cards are a bit oversized too, but that is probably a very subjective opinion so I’ll close the bug.
