### ISSUE TITLE
Unable to make new account using same email after deleting old account

### ISSUE THREAD

**Issue by flux77** [bookwyrm-social/bookwyrm#2911]
**Describe the bug**
I deleted my Bookwyrm account some time ago, and I now want to make a new account. However, I am unable to register for a new account. Bookwyrm complains: "User with this Email already exists." Could it be that I am attempting to register using the same email that was associated with the deleted account? That is weird behavior. Why can't I register using the same email address that was used in a deleted account?

I see that there is #1445, but the "solution" there is atypical and completely surprising for web applications.

>re-registration can still be done by using the + syntax supported by most email providers

**Instance**
https://bookwyrm.social

**Comment by mouse-reeve** [comment]
Thank you for digging up the prior work on this one, it is something people email me about periodically but I didn't have any recollection of that specific issue. And while I agree (with myself, in the past) that it's a usable workaround for some cases, I agree with you that it's a weird resolution to the issue!

**Comment by Retr0mantic** [comment]
I’m having this same issue right now, I’m locked out of using my email address.

**Comment by Retr0mantic** [comment]
What is the + syntax workaround? Will that enable me to use my email address again?

**Comment by mouse-reeve** [comment]
Some email providers (like gmail) allow you to add anything you want to the end of your address with a plus sign, so `example+anything@gmail.com` will work fine if your email address is `example@gmail.com`

**Comment by Retr0mantic** [comment]
OK, I ‘think’ it has worked, but I need the system to send an email really to know for sure. I guess the fact I haven’t had an email confirmation email is a red flag.

Is there any way the database or whatever could be manually edited so I can use my proper email address? This feels weird and I really don’t want to change instance just for this. Especially because trying to move my history etc from one account to another is what got me in this mess in the first place!

**Comment by Retr0mantic** [comment]
Either that, or can you restore my old account so I can log in and change the email address before deleting it again?
