### ISSUE TITLE
Question: When I approve federation do I approve only for my site or for everybody?

### ISSUE THREAD

**Issue by airdogvan** [bookwyrm-social/bookwyrm#2950]
Thanks for answering...

**Comment by hughrun** [comment]
Good question @airdogvan 

You are approving federation for your server only. However, because of the nature of federation this can have downstream effects on servers that federate with you, since some of your server's data will now come from the server you just federated with.

The primary reason you would _manually_ add a site is if you want searches for books to query that server as well. Normally federation happens "organically" as you add books from the initial federation targets (e.g. `bookwyrm.social`) and users on your server follow and are followed by users around the fediverse.

This also applies to server level federation blocking, just as in other fediverse software: if you block `mean-bookwyrms-example.com` from federating, that will only apply to your server.

Hopefully that is clear? We probably need to add more information for server admins to the documentation.

**Comment by airdogvan** [comment]
Thank you.  I think I understand.  Yes, yesterday when I approved a few I was thinking: "what if I approve for the whole network of bookwyrm"?
But you're right, because of propagation, approving for my site increases the chances of propagation...
Thanks again
