### ISSUE TITLE
CSV export does not include read date

### ISSUE THREAD

**Issue by ccamara** [bookwyrm-social/bookwyrm#2965]
**Describe the bug**
When exporting data into a CSV file, several fields are exported, but `read date` is not one of them, despite being exremelly valuable.

**To Reproduce**
1. Go to 'Profile'
2. Click on 'Export to CSV'
3. Download CSV file
4. Open CSV file

**Expected behavior**
A column containing read date should be included among the current ones

**Instance**
bookwyrm.social

---

**Desktop (please complete the following information):**
    - OS: KDE Neon
    - Browser Firefox, Chromium
    - Version

**Comment by ccamara** [comment]
I've been wanting to contribute o bookywrm for a while, and I suspect this could be a good first issue,

I believe that this could be fixed by adding a new line here https://github.com/bookwyrm-social/bookwyrm/blob/e5f8e4babc3cc11ac7eb5b1bdbd5bdc9ced48fd2/bookwyrm/views/preferences/export.py#L32-L38

However,  I'm no very good at python and never worked with django, so I'm not sure what should I do next. I believe that with little guidance I'd be able to fix that myself.

**Comment by hughrun** [comment]
Welcome @ccamara! I can help you with this.

The line you've pointed to is creating a `set` of books based on a series of searches. We're already bringing in `books_readthrough` so that tells us all the books the user has some kind of reading activity for. So we have the books, but we need the `ReadThrough` data.

The way to do that is probably to follow the pattern used for finding reviews and adding review data to the export: https://github.com/bookwyrm-social/bookwyrm/blob/e5f8e4babc3cc11ac7eb5b1bdbd5bdc9ced48fd2/bookwyrm/views/preferences/export.py#L67 There are more efficient ways to do this since not every book will have a ReadThrough, but most will and this is the easiest way to do it without rewriting half the export function.

Check out `models.ReadThroughs` to see what information is available. You can see we would get a number of different dates, and a `progress_mode`. Perhaps we want to export all of that so it's clear what the date relates to (i.e. "stopped" date is very different to "read" date). If you did that you would need to [add those to the `fields`](https://github.com/bookwyrm-social/bookwyrm/blob/e5f8e4babc3cc11ac7eb5b1bdbd5bdc9ced48fd2/bookwyrm/views/preferences/export.py#L48) so there's an appropriate header and column in the CSV

There is another issue here: https://github.com/bookwyrm-social/bookwyrm/issues/2846 which is about adding the shelf name in the export. Including the ReadThrough `progress_mode` would go some way to resolving this but not include custom shelves. You don't need to worry about this as I don't want to scope-creep your first contribution, I'm just mentioning it for completeness and so the issues get linked.

**Comment by ccamara** [comment]
Thank you so much for the super useful explanation, @hughrun !

It has taken me a lot to finally try to fix this (I struggled with the bookwyrm setup, I have no experience with django...) but I finally managed to try to fix this and submitted this PR: #3189

I'm not sure if that's the best way to do it (to be honest, there are still many things I do not fully understand, but I followed your explanation and looked at the existing code), but it works in my environment. Feel free to review and suggest any improvements.

**Comment by hughrun** [comment]
Nice one!

I'll take a look. When I made my first PR for BookWyrm I'd never used Django either 🙂.
