### ISSUE TITLE
Incorrect behavior when the 'Add another edition' button is in a foreign language.

### ISSUE THREAD

**Issue by fofwisdom** [bookwyrm-social/bookwyrm#3020]
**Describe the bug**
Even if you click the 'Add another edition' button, it will add editions based on the book's title search criteria, so non-English names are added as new books.

**To Reproduce**
1. Search the book
2. Click on 'Add another edition'
3. Putting the title of the book in the language of the translated edition.
4. Adding an edition failed

**Expected behavior**
Add a new edition by specifying the book for which you clicked 'Add another edition'

**Screenshots**
![image](https://github.com/bookwyrm-social/bookwyrm/assets/205521/2aca9978-2d8d-4db5-b13c-82b231697448)

**Instance**
https://reads.netsphere.pub/
https://bookwyrm.social/

**Additional context**
BookWyrm does not have the feature to merge books, so this behavior causes server users to lose information about all editions forever.

New users attempt to contribute and are frustrated by this problem and leave the service.

**Comment by dato** [comment]
Thanks for reporting.

I believe this was fixed recently by @jderuiter in 05f8bd0d3c500e91585253ad9e5c393a11aba58b, and will be included in the next release.

If you control your instance, you can edit that file as shown, if it's urgent to correct this behavior.

***

For others reading along: I think `form.parent_work` could be safely dropped from the template, since the form does not have such field, and no code ever sets it explicitly (that I can see).

**Comment by fofwisdom** [comment]
It's fixed in v0.6.6, which was released a few days ago, thanks for the feedback!
