### ISSUE TITLE
Please make it possible for non-docker installations to switch to S3 compatible storage as well.

### ISSUE THREAD

**Issue by PrivacyDragon** [bookwyrm-social/bookwyrm#3065]
**Is your feature request related to a problem? Please describe.**
Since book covers take up a lot of my available storage, I need to get rid of them. I tried simply deleting them all (after having made a backup), but I think that caused problems that I am not going to explain here, for that's not directly related. I had to move them back, but now there is almost no storage space left on the server, so I need to switch to using external storage.
However, following the guide in the documentation does not work. the `bw-dev` command complains that I do not have docker installed.
I tried to replace `bw-dev` with `./manage.py`, as should usually work. However, it looks like the `copy_media_to_s3` option has only been implemented for people lucky enough to use Docker. The python program tells me that `copy_media_to_s3` is not a valid option.

**Describe the solution you'd like**
I would like to be able to copy my media to an s3 compatible server.
It feels like dockerless installations have been forgotten.

**Describe alternatives you've considered**
I am not going to upload more than 50,000 files manually...

**Comment by hughrun** [comment]
Hi @PrivacyDragon 

Thanks for logging this. BookWyrm is a young project with a very small group of regular maintainers. For this reason most development is done within the Docker paradigm, as that allows us to control the environment in which BookWyrm is expected to run without having to work out every conceivable combination of operating system quirks.

`./bw-dev` is a series of convenience shell script functions. Because it assumes you are running Docker, we can use the [Amazon ECR Docker Hub image](https://docs.aws.amazon.com/cli/latest/userguide/getting-started-docker.html) on demand for any s3 functions.

It may be that we need to look into making a "dockerless" equivalent of `./bw-dev`, since most commands are intended for use with docker, however for dockerless installs it is more difficult to build equivalent commands, as it will be dependent on what libraries and command line programs are installed on your machine and these cannot be assumed. 

In the meantime, you should be able to migrate file from your server to s3 using one of these CLI applications:

* [Amazon s3 CLI](https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html)
* [open source CLI application `s3cmd`](https://github.com/s3tools/s3cmd)

**Comment by PrivacyDragon** [comment]
Thank you very much for providing a way to migrate the files.
Maybe it is an idea to include them in the guide (until an alternative is found)?
