### ISSUE TITLE
Importing from OpenLibrary assigns publication date to "today"

### ISSUE THREAD

**Issue by stopregionblocking** [bookwyrm-social/bookwyrm#3129]
**Describe the bug**
If a book on OpenLibrary gives the publication date as a Gregorian calendar year, Bookwyrm adds the current month & day to that date, rather than just leaving the year

**To Reproduce**
1. Search for a work on Bookwyrm
2. Load results from other catalogs (if not already visible)
3. Import a work from OpenLibrary that isn't already on Bookwyrm

**Expected behavior**
The (Gregorian year) publication date should be displayed without invented details not included in the original data, like the current month & current day of the month 

**Instance**
Main instance

**Additional context**
I have not tested to see how works whose publication dates on OpenLibrary *do* include months & days import.

**Comment by dato** [comment]
Hello! Thank you for your bug report.

Yes, this is a known issue that has been fixed recently. It should be part of the next release.

Details:

- bug #2660 (partially addresses your report): instead of today's data, use 1/1 to complete OpenLibrary dates
- bug #743 (fully addresses your report): allow storing incomplete publication dates (e.g., only year)
