### ISSUE TITLE
let users add books to their shelves by scanning ISBN / barcodes

### ISSUE THREAD

**Issue by hartsick** [bookwyrm-social/bookwyrm#318]
**Describe the solution you'd like**
In Goodreads mobile app, you're able to add books to your shelves by scanning the barcode / ISBN from the back of a book. At this time, you can also assign shelves. In the past, I've used this as a way to track books I'm interested in reading and also my personal library. Would be cool to have this option in Bookwyrm, too!

**Comment by mouse-reeve** [comment]
https://github.com/NaturalHistoryMuseum/pyzbar

**Comment by viviicat** [comment]
I'm looking into potentially working on this (I've already done some mockups for myself).

However I'm wondering if it would be simpler to use a barcode-scanning JS library instead of pyzbar (either [html5-qrcode](https://github.com/mebjas/html5-qrcode) or some custom WebRTC JS to capture a still image and pass to [zxing-js](https://github.com/zxing-js/library)). I was unsure as to whether that would bulk the JS codebase up too much for your taste, though. The upside would be that it would all be client-side which privacy-minded users could appreciate.

**Comment by mouse-reeve** [comment]
I'm open to either approach -- can you expand on what you mean about privacy for the client-side approach?

**Comment by viviicat** [comment]
I guess the point on privacy is mostly irrelevant--it was just a minor observation that because nothing is sent to the server, the user wouldn't be worried that the instance owner has altered the sourcecode and is somehow saving the image on the server--in case the image unintentionally had something in the frame the user didn't want stored in addition to the barcode.

I'm not super familiar with this stack, but another upside may just be that the server doesn't need to queue up a process to analyze the image and then discard it, a process that, if very frequent, could be a bit intensive.

And if we use the first JS library, it analyzes multiple frames to search for a code, so the UX is a little nicer (instead of having to capture a particular image, then wait for the server to analyze, then possibly start again if the image was blurry, etc).

**Comment by mouse-reeve** [comment]
I see, thank you! I think you're quite right that having the client do the work of scanning the image would be big benefit.
