### ISSUE TITLE
Privacy for All Books and old posts (Followers only or fully private)

### ISSUE THREAD

**Issue by christianepeters** [bookwyrm-social/bookwyrm#3200]
I can see how to change the default posting visibility.

I don’t see how to change visibility of already made posts retroactively as one action for all posts.

I can see how to change visibility on shelves.

I don’t see how to change the visibility of the All Books shelf.

I don’t see how to bulk delete all my books to reimport and start over. 

Am I missing something or is it just not possible to change visibility on overall activities after posting?

thanks for your help.

**Comment by hughrun** [comment]
> I don’t see how to change visibility of already made posts retroactively as one action for all posts.

> Am I missing something or is it just not possible to change visibility on overall activities after posting?

This is not currently possible, though it's a good idea. A caution on this though - changing the privacy settings doesn't necessarily change who can see your post on federated servers, due to how federation works. Mastodon, for example, doesn't let you change the visibility on a post at all, presumably so as not to mislead people on this. If you have already posted something as "public" it will have federated out to other servers. If you then retrospectively change it to "followers", those servers will still have your post and won't necessarily remove it for actors who are not following you.

> I don’t see how to change the visibility of the All Books shelf.

You can't edit any settings for "All Books" as it's not a "real" shelf. However books inherit the visibility of the other shelf/s they are on. i.e. if you set privacy of "To Read" to `followers`, books from that shelf will not be visible in "All Books" to users who are not following you.

> I don’t see how to bulk delete all my books to reimport and start over.

You're right that it is not currently possible to bulk-edit your books. Can you explain a little more what your desired use-case is here? Would the intention be to delete _all_ book-related data (books on shelves, readthroughs, statuses, lists..) or something more limited? Are you talking about BookWyrm user imports, or book data imports from e.g. Goodreads?

**Comment by christianepeters** [comment]
Thank you for the detailed explanation.
This helps. Basically I will have to delete my account given that all I did already federated out while I would prefer to have it shared with logged in users only and not with the whole internet.
