### ISSUE TITLE
Export tasks run for a long time

### ISSUE THREAD

**Issue by mouse-reeve** [bookwyrm-social/bookwyrm#3203]
When a user starts an account export, the entire thing is handled in a single celery task. For a user with a lot of data (like me), that ends up being a huge undertaking and the task runs for a really long time -- I have one currently running that is at 20 minutes and counting. If an instance only has one worker thread, this would block important site functionality until the task completes.

**Comment by hughrun** [comment]
When we were working on this it was originally split into multiple tasks but for reasons I can't remember it ended up being merged into one. I think from memory this wasn't a technical issue, more that it was getting a bit confusing for those of us less familiar with Celery. So ...it might not be too hard to split them out again?

**Comment by hughrun** [comment]
I've been doing some work on this to split the exports into individual tasks for each file that is added.

I'm most of the way there in terms of Job/Task management, but what has become clear whilst testing this is that the behaviour when using s3 is quite different than with local file storage. I believe this is the reason for the problems we've been seeing with user exports including #3204.

The issue seems to be that when we try to Tar a file that's stored remotely, the files can't be found. I'm still trying to nail down whether this is simply due to filepaths differing, or whether it's more fundamental than that.

For now, I **strongly recommend** that we need a quick patch to enable admins to switch off the ability to create user exports until this is resolved.

cc @mouse-reeve @bookwyrm-social/code-review

**Comment by hughrun** [comment]
Resolved in #3228
