### ISSUE TITLE
Account import from another instance fails

### ISSUE THREAD

**Issue by mapperfr** [bookwyrm-social/bookwyrm#3292]
I'm trying to import to a Yunohost self hosted instance an account archive previously exported from another instance. The import fails. I've tried three times.

Here are the steps I followed:

- I imported my archive from [the instance I was previously using](https://bw.heraut.eu). Here's the exported archive for reference: [240204_bookwyrm-account-export.tar.gz](https://github.com/bookwyrm-social/bookwyrm/files/14373949/240204_bookwyrm-account-export.tar.gz)
- On the instance [I want to migrate to](https://b.falai.se), I set the previous account as an alias.
- Tried to import the the archive on the new instance. It fails (see screenshot).

![Screenshot_20240222_133521](https://github.com/bookwyrm-social/bookwyrm/assets/3398608/842a5455-3db7-44c9-8a53-db0eeb215e39)

---

**Bookwyrm technical context**
    - Previous instance (https://bw.heraut.eu): ?
    - Current instance (https://b.falai.se): Bookwyrm 0.7.2~ynh1 on a Raspberry Pi 4 (Olimex A20, lime2. Debian Buster) with Yunohost 11.2.10.1 (stable).

**Desktop (please complete the following information):**
    - Ubuntu 23.10
    - Firefox 123

**Comment by prolibre** [comment]
Hello @mapperfr 
I am the administrator of the bw.heraut.eu instance :-)
For info the version is 0.7.2 too (with the last update of the prod). Boowkyrm is installed under a debian (without docker).

**Comment by hughrun** [comment]
@mapperfr do you have access to any error logs for this?

**Comment by mapperfr** [comment]
> @mapperfr do you have access to any error logs for this?

Not that I'm aware of. I looked into the NGINX logs (can't ssh right now to check the exact path) but couldn't find a Bookwyrm log that would explain the issue.

**Comment by hughrun** [comment]
Ok I've found the problem: the cover URL for _Roccanon's World_ is listed in the export JSON file as `covers/Capture_d%C3%A9cran_du_2023-11-13_21-04-02.png` but the filename is `Capture_décran_du_2023-11-13_21-04-02`.

It appears that [`JSONEncoder` defaults to `ensure_ascii=True`](https://docs.python.org/3/library/json.html#json.JSONEncoder) which seems like a surprising default for Python 3 but there you go.

I've done a very quick test setting `ensure_ascii=False` in `DjangoJSONEncoder` but I'm not sure whether that works because something - either Django or my filing system - seems to simply be stripping out the accent rather than leaving it or escaping it.

**Comment by mapperfr** [comment]
Thanks @hughrun! 

I've tried to manually modify the JSON by replacing `covers/Capture_d%C3%A9cran_du_2023-11-13_21-04-02.png` with `covers/Capture_décran_du_2023-11-13_21-04-02.png`, the import failed again. 

My next move will probably be to:
- un-move my previous account, 
- change _Rocannon's World_ cover with another accent-less named file, 
- export the data,
- check for potential diacritic accents and other non ascii characters, 
- move the original account again, 
- try importing again.

Any other suggestions are welcome of course.

**Comment by hughrun** [comment]
Thanks for logging this bug. We need to fix the underlying problem but that may take a while to get into production so in the meantime your plan sounds good.
