### ISSUE TITLE
External Link Modal confirmation window

### ISSUE THREAD

**Issue by xmgz** [bookwyrm-social/bookwyrm#3371]
please anyone could confirm this issue? 

In my opinion is a bug 

**Describe the bug**
there's no UI element to take action in the "get a copy" external link modal

**To Reproduce**
1. Go to a book that has an External Link (Get a copy from this book): **[Example](https://lectura.social/book/113225/s/las-redes-son-nuestras)**
2. Click on the link (a web link well formed)
3. then a modal window opens with the full link and asking confirmation to leave bookwyrm instance
4. but there is no accept/reject button and the link is not clickable, one just can click on the "X" to close the modal

**Expected behavior**
some UI element to accept/reject following the link

**Instance**
https://lectura.social

**Additional context**
none in particular, just reading about this book https://lectura.social/book/113225/s/las-redes-son-nuestras as a non-logged in user

**Screenshots**

### This is the modal that opens after clicking in the link

![pantallazo_20240529_055109](https://github.com/bookwyrm-social/bookwyrm/assets/704948/c6338c77-6212-42e1-b6c2-3a50b2944a65)

### This is the "Get a copy" section in the book's page

![pantallazo_20240529_055006](https://github.com/bookwyrm-social/bookwyrm/assets/704948/43874009-190c-4170-9af8-a1680b18ed29)

---

**Desktop (please complete the following information):**
- firefox 126.0 in Archlinux
- no browser extensions (adblockers, etc.) seem to be blocking anything in this domain

**Comment by timothyjrogers** [comment]
I'm able to reproduce this on [books.infosec.exchange](https://books.infosec.exchange) which (at time of writing) is on Bookwyrm version `0.7.3` as well as in my developer environment on current `main` code.

The behavior appears correct when logged in -- the modal provides me the option to continue to the link or back out -- however when not logged in I get the do-nothing modal you describe.

When logged in:

![image](https://github.com/user-attachments/assets/410832b1-e88e-4e9b-a6a5-4607f0f4297f)


When logged out:

![image](https://github.com/user-attachments/assets/24dba3cf-a5ea-4c60-95a3-b7e546ecce4b)

**Comment by timothyjrogers** [comment]
This issue is caused by the template code in the verification modal here: https://github.com/bookwyrm-social/bookwyrm/blob/main/bookwyrm/templates/book/file_links/verification_modal.html#L20-L27

All three buttons ("Report Spam", "Cancel", and "Continue") are all wrapped in the authentication check which renders zero options when you are logged out. I assume this was added to prevent abuse of the spam reporting feature by unauthenticated users/bots, but leaving an essentially dead modal seems unintentional.

It's trivial to fix, I'll submit a PR reducing the authentication check to the "Report Spam" link. If a more knowledgeable maintainer can explain why the other two buttons would need an authentication check we can explore a more detailed fix.
