### ISSUE TITLE
Not a bug but problem for me

### ISSUE THREAD

**Issue by airdogvan** [bookwyrm-social/bookwyrm#3406]
I wanted to change my docker volumes to bind mount.  I created local folders with the same name as volumes, copied the data and tried to restart docker-compose up and got the following error:
```Building celery_worker
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.```

The only thing I changed in the compose file is the volume mount from:
```  celery_worker:
    env_file: .env
    build: .
    networks:
      - main
    command: celery -A celerywyrm worker -l info -Q high_priority,medium_priority,low_priority
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/images```   
   to
```  celery_worker:
    env_file: .env
    build: .
    networks:
      - main
    command: celery -A celerywyrm worker -l info -Q high_priority,medium_priority,low_priority
    volumes:
      - .:/app
      - ./static_volume:/app/static
      - ./media_volume:/app/images```

Tried setting up the DOCKER-HOST environment in .env (which I shouldn't have to do as from cli docker is accessible) but still got the same error.

Also tried returning to docker volumes with the same result.  Now stuck!


Any help greatly appreciated.
Thanks

**Comment by hughrun** [comment]
Hi @airdogvan, sorry to hear you are having trouble.

The most likely scenario is that your `bookwyrm` user (or whatever you're using to run docker) doesn't have permission to read your new directories. So the first thing I'd do is `ls -l` and check which user owns your volumes/directories on the host.

Failing that, check your environment variables:

* check you are setting `DOCKER_HOST` rather than `DOCKER-HOST`
* `.env` variables are available _inside_ the container - they are not available to the docker daemon itself - for that you need an environment variable set on the host. So you may need to run something like `DOCKER_HOST=127.0.0.1:2375 docker compose up`

**Comment by airdogvan** [comment]
How did you guess that it was a folder permission problem??? What's the connection between "cannot connect to docker" and folder permissions?  Been dealing with docker for quite a while now and never would have guessed!

Anyway, that's the second time in 30 days that you guys take me out of a tight spot.  I owe you one, or two.  If there's anything I can do for you, don't hesitate to contact me!

**Comment by hughrun** [comment]
> How did you guess that it was a folder permission problem??? 

I'm a librarian, I'm good at finding answers ;)
