### ISSUE TITLE
10-star scale

### ISSUE THREAD

**Issue by texttheater** [bookwyrm-social/bookwyrm#556]
**Is your feature request related to a problem? Please describe.**
I always get frustrated when I'm forced to rate a book I liked and 3, 4, or 5 stars are the only options. It's not enough nuance. My mental hierarchy of favorite books has more layers than that. For example, many books are deserving of more than the middling rating of 3, but I wouldn't rank them as high as those I rate 4. Similarly, some books are extremely outstanding, but still don't quite deserve the absolute maximum rating. I don't have this problem at all with films on IMDb, the 10-star scale feels exactly right.

**Describe the solution you'd like**
The 5-star scale should be replaced with a 10-star scale. Existing reviews should be adapted by doubling the number of stars.

**Describe alternatives you've considered**
Half-stars would be an equally good alternative.

**Additional context**
n/a

**Comment by rkingett** [comment]
Ironically, if it were 10 stars for me, then I would take forever rating a book! I think this is a good suggestion though. I would like to ask that this could be a user preference?

Like, in our accounts we can tell the system what star rating we would like to use?

I like this suggestion!

**Comment by mouse-reeve** [comment]
I have a strong preference against a 10 star scale personally, but I'd be perfectly happy to have half star support

**Comment by mouse-reeve** [comment]
thank you both for the suggestions! my feeling is that having separate rating scales would be confusing and hard to maintain, but opt-in half stars would be a reasonable compromise to let strict 5-stars-ers like me stay at a scale we can manage, and give more nuance to people who prefer a 10 star scale

**Comment by rkingett** [comment]
Yes. I love the half star feature more! Fun fact, Goodreads never had half stars and thousands wanted it.

**Comment by arkhi** [comment]
@texttheater: I’m curious about what the meaning of a 1 to 5 are for you in a 10-based scale as I believe this is highly dependant on the culture as well. My goal in asking this question is to understand how we humans work as everything is getting rated these days and I feel it’s important to understand nuances.

I find it interesting you’re writing that 3 is a middling as, for me, this is the reason why I prefer 5 steps to 10. An odd scale forces me to take a decision on if I liked or disliked something because 3 is already more than the middle, whereas rating something 5 feels like an absence of decision (to me :) ). I end up rating on a 5‑based scale no matter what (2, 4, 6, 8 and 10), which sums up like:

0. No rating
1. or 2/10: It was painful.
2. or 4/10: I did not like it.
3. or 6/10: It was OK.
4. or 8/10: It was good.
5. or 10/10: It was amazing.

**Comment by Flameborn** [comment]
I think that this is really dependent on whether you associate a label to the rating or not. Choosing from 1 to 5, for example, at least to me, is a lot easier than if I associate labels to the scale values.

10 stars would be five too many, I think, but if we add half stars, what's 0 and a half going to be?

**Comment by rkingett** [comment]
For me, 5 stars is better. Besides, I care about the reviews more than the star ratings.

**Comment by Flameborn** [comment]
This just happened to me, as I was importing Goodreads books and rated them.

One book got 4 stars, because I really liked it, another got 4 as well, even though I liked it more than the previous 4, so theoretically this would be 4 and a half. Then came another book, which got 5 stars, simply because it would've been better than 4 and a half, aka. the previous book, but it was definitely not as amazing as compared to my very first 5-star book I read.

So, having half stars would have solved my issues, somewhat, but as you can see the more you drill down into fine-scaled ratings, you will end up wanting more control, until you reach a 1 to 100 star system. If we compare a rating to previous ones, it might happen that finding the perfect value is impossible.

I am not trying to dismiss this request, just throwing in what I experienced right now, along with my opinion, for what it's worth.

**Comment by texttheater** [comment]
This does not match my experience, @Flameborn. I have used IMDb's 10-star scale for many years and never found I wanted it more fine-grained. I guess it hits the sweet spot for me.

**Comment by TomatDividedBy0** [comment]
I second a half-star approach. 10 stars sounds like it'd take up too much space on the interface.
