### ISSUE TITLE
Make finding my comments and quotes easier

### ISSUE THREAD

**Issue by tastytea** [bookwyrm-social/bookwyrm#737]
**Is your feature request related to a problem? Please describe.**
I sometimes want to look up a comment I made on a book or a quote.

**Describe the solution you'd like**
I think it would be useful to display my comments and quotes on book pages.

**Describe alternatives you've considered**
The only other option is to scroll through the home timeline or my profile page, as far as I'm aware.

**Comment by mouse-reeve** [comment]
This is sort of intentional -- I set up the book page to only show reviews so that comments and quotes could be posted in a way that felt more transient. I also delete my old posts on mastodon and twitter. But that's my personal preference for social media, not an objectively correct design principal.

A solution that comes to mind which I think balances both desires is to a tab on the book page, in the reviews region, for the current logged in user's comments and quotes on the book. That would make your posts about the book readily accessible, but only to you. Does that seem like it would satisfy what your concerns are?

**Comment by tastytea** [comment]
Yes, I meant that it should only be visible for me. 🙂

**Comment by LongJohn-Silver** [comment]
I think quotes could, optionally, be public. I like how you can see author's quotes on GR and like them, and how you could link them to your profile either by liking them or creating them.
