### ISSUE TITLE
data export

### ISSUE THREAD

**Issue by mouse-reeve** [bookwyrm-social/bookwyrm#75]
you should be able to download your bookshelves and review data

**Comment by arkhi** [comment]
I was wondering if there is a standard and found many based on a [quick search about library exchange format](https://www.minitex.umn.edu/services/digital-initiatives/standards-digital-collections/data-format-exchange-standards).

Do you already know which one you wanted to implement?

**Comment by mouse-reeve** [comment]
I think something like MARC wouldn't be a good fit here - I'm envisioning just a csv, similar to what you might download from goodreads or librarything. The data being downloaded is mostly user data, rather than library metadata.

**Comment by TheGameFreak720** [comment]
I'm wondering if it would be ok for me to work on this since I heavily need a CSV export to have backups stored just in case.

**Comment by mouse-reeve** [comment]
Yeah! Let me know if you have any questions 😄

**Comment by TheGameFreak720** [comment]
I'm waiting for a laptop I bought to arrive to work on this task. Apart from it being a CSV that is compatible with GoodReads. Do you have any set requirements for this particular task? Code style guidelines? In my case the requirements I always have is to check for accessibility, make sure if there is a way to test it to add that, and test for edge cases.

**Comment by mouse-reeve** [comment]
I think goodreads compatibility is a good baseline; it shouldn't be too hard to add columns if there's something people would find useful in the future. 

It may make sense to make the generation of the csv file happen in a celery task to avoid backing up the main site process - I'm just basing that on how other services serve CSVs.

I went ahead and wrote a basic code style thing for the documentation rather than stream my conscious out here - let me know if there's info that would be helpful to add there: https://github.com/bookwyrm-social/documentation/pull/17

**Comment by TheGameFreak720** [comment]
Good to know. I will research the celery task when I get setup with that new computer that Dell refuses to send. If push comes to shove I'll set a VM for this task because I like the app a lot and use it.

**Comment by mouse-reeve** [comment]
Since it all runs in docker, getting celery running _should_ be a non-issue (if you're using docker). But let me know if you run into any weirdness!

**Comment by TheGameFreak720** [comment]
I finally got a laptop and I haven't set up a service with Nginx in a very long time. At least not locally so trying to figure that out in the meantime. Since it doesn't specify directories or how exactly to set it up without having done it before on the same app or elsewhere I'm going to poke at it for a bit.

**Comment by TheGameFreak720** [comment]
Quick update I think I'm doing good. The docker compose is doing most of the work. Just that initial part was a bit confusing without seeing the codebase.

**Comment by TheGameFreak720** [comment]
I'm running into some issues when running this command `docker-compose run --rm web python manage.py migrate`. 

```
Creating bookwyrm_web_run ... done
python: can't open file '/app/manage.py': [Errno 13] Permission denied
ERROR: 2
```

One thing that might be another issue is that the Dockerfile has this last command `RUN apt-get update && apt-get install -y gettext libgettextpo-dev && apt-get clean` and I'm running Fedora 34. Not Ubuntu. Let me know if there is something I'm missing on the docker-compose or if we can connect to get this initial setup. I will try and repay that back with some UI enhancements.

**Comment by mouse-reeve** [comment]
The `apt-get` commands are running in the docker container, so it shouldn't matter what operating system you're running (I'm on a mac, for example, which doesn't support `apt-get`), just what the docker image is installing. 

I wonder if you're hitting a system permissions problem with docker? This isn't a long term solution, but does it run with sudo?

This is what I found looking around briefly:
https://stackoverflow.com/a/60818019
https://docs.docker.com/engine/install/linux-postinstall/
https://linuxconfig.org/how-to-install-docker-on-fedora-linux-system#h2-run-docker-without-root

**Comment by TheGameFreak720** [comment]
My theory is that the docker user might not have the permissions to do the action. I have been running it with sudo, but still run into the issue. I haven't found a way to test this before adding any permission that might be problematic. Will be taking a look at those resources later in the day, cause right now I'm at work.

**Comment by seniorm0ment** [comment]
Cannot help specifically with the issue, however I see you mentioned backups. 
When implemented could anything be done such as a script ran on cron to automatically download backup copies of user profiles periodically? This may need an api token, which I don't think bookwyrm has implemented if I am correct?
This is something I'd be interested in, because instances can go down or die anytime, it would be nice to not just lose everything if it happens. Backups are good.

**Comment by mouse-reeve** [comment]
> Cannot help specifically with the issue, however I see you mentioned backups.
> When implemented could anything be done such as a script ran on cron to automatically download backup copies of user profiles periodically? This may need an api token, which I don't think bookwyrm has implemented if I am correct?
> This is something I'd be interested in, because instances can go down or die anytime, it would be nice to not just lose everything if it happens. Backups are good.

I think this is off topic for this issue, it would be closely related to #1012. Handing that in cron would likely be on the user end, not the application end.

**Comment by seniorm0ment** [comment]
How is it off topic? All I was suggesting was the ability to automatically download the data export file periodically + an api token to connect without needing to use username/password.
Both this issue #75 and #1012 are both related however they are asking two different things. 1012 is requesting direct migration to another instance (which could also be done through data export), and 75 is requesting a CSV data export to be stored locally.

@TheGameFreak720 literally said
>work on this since I heavily need a CSV export to have backups stored just in case.

I was simply adding the suggestion of additionally providing users a basic script they could use, and api token for users to automatically grab these exports instead of needing to do it manually (and risk having outdated exports). The script could then be placed on any system (like cron) of the users choice. 

I fail to see how my suggestion is off topic at all.

**Comment by mouse-reeve** [comment]
Thank you for the clarification - I thought you were referring to backing up user account data that could be used to move instances specifically (so, more like the data you would need to migrate accounts, as opposed to the type of data you'd get from a Goodreads csv export, which has the books you've catalogued, but not other information about your account).

Adding support for API keys would be a first step to helping users automate tasks like backing up their data via CSV export, and you are right that that hasn't been implemented yet.

Apologies for the confusion - I didn't mean to be harsh, I'm just trying to keep individual issues pretty granular and focused so that the scope of the work is clearer.

**Comment by TheGameFreak720** [comment]
To talk for myself, I meant just a button that I can get a CSV export because that is the bare minimum I need. Would be nice for automatic backups, but that gets complicated quickly and in my view out of scope for this task.

**Comment by TheGameFreak720** [comment]
That being said, in an alternative issue I have worked with queue servers using Redis and can give suggestions on how to do it. For myself, I rather work on this and some UI as long as @mouse-reeve approves.

**Comment by mouse-reeve** [comment]
For sure @TheGameFreak720 - please work on what you're interested in

**Comment by TheGameFreak720** [comment]
I've been trying to get this app to run between last night and today. I fixed most of the docker and docker-compose setup. The way I did it was using these 2 guides:

* https://docs.docker.com/engine/install/fedora/
* https://docs.docker.com/engine/install/linux-postinstall/

Then docker-compose: https://developer.fedoraproject.org/tools/docker/compose.html

Only thing I did there was install the package. 

I was able to run [ArchiveBox](https://github.com/ArchiveBox/ArchiveBox) that I believe is a Django app as well. I'm still running into issues with this one, but different ones:

```
[zero@skeletor bookwyrm]$ docker-compose run --rm web python manage.py migrate
Starting bookwyrm_redis_broker_1 ... 
Starting bookwyrm_redis_activity_1 ... error
Starting bookwyrm_redis_broker_1   ... error

ERROR: for bookwyrm_redis_activity_1  Cannot start service redis_activity: OCI runtime create failed: selinux label is specified in config, but selinux is disabled or not supported: unknown

Starting bookwyrm_db_1             ... error

ERROR: for bookwyrm_db_1  Cannot start service db: OCI runtime create failed: selinux label is specified in config, but selinux is disabled or not supported: unknown

ERROR: for redis_activity  Cannot start service redis_activity: OCI runtime create failed: selinux label is specified in config, but selinux is disabled or not supported: unknown

ERROR: for redis_broker  Cannot start service redis_broker: OCI runtime create failed: selinux label is specified in config, but selinux is disabled or not supported: unknown

ERROR: for db  Cannot start service db: OCI runtime create failed: selinux label is specified in config, but selinux is disabled or not supported: unknown
ERROR: Encountered errors while bringing up the project.

```

If you know what this could be I would appreciate it. I haven't found much on this specifically

**Comment by TheGameFreak720** [comment]
This forum post says it's not possible, but I have been digging and SE-Linux currently is disabled hence why these errors are popping up. I would need to enable this service in order to hopefully get the app running. Will try tomorrow morning

* https://serverfault.com/questions/757606/how-to-enable-selinux-inside-of-a-centos-docker-container

**Comment by TheGameFreak720** [comment]
I haven't forgotten about this. Just been busy with work and personal.

**Comment by TheGameFreak720** [comment]
Unfortunately, if I'm using Fedora it is not possible to run containers that have an SELinux policy. Seems to me that is more of [an enterprise feature for CentOS](https://www.arhea.net/posts/2020-04-28-selinux-for-containers.html) for having policies in containers. You can [enable SELinux](https://docs.fedoraproject.org/en-US/quick-docs/getting-started-with-selinux/), but I don't know too much about it to make that judgement in my local machine. This seems to be a feature for VM's exclusively, and one of the blog posts above says that. I'm very unsure this will be possible with Fedora and might have to allow someone else to take it until I get another Distro since virtual machines can be a pain to code in and more in my not so powerful laptop.

**Comment by seniorm0ment** [comment]
podman maybe?

**Comment by TheGameFreak720** [comment]
Maybe, I've never used it. I can look into it just that I'm a beginner in Docker and this feels like a deep end where I could make my machine vulnerable if not done correctly.

**Comment by WorldsEndless** [comment]
Kind of embarrassing how easy this was on the thing we are replacing (goodreads) but isn't yet possible here
