### ISSUE TITLE
Grouping Things

### ISSUE THREAD

**Issue by arkhi** [bookwyrm-social/bookwyrm#798]
I am opening this Issue to discuss something that I find myself a bit uncomfortable with.

At the moment, I see a few different ways to group things together and I’m not entirely sure about what differentiates them:

- Shelves
- Lists
- Tags
- Subjects
- More?

I wonder if there is a clear definition and use for them. Sorry if it’s already documented somewhere that I did not find; I’m just always wondering if something can be simplified. :)

**Comment by mouse-reeve** [comment]
It's not documented, thank you for raising this!

This is my mental model:
- Shelves: a set of lists of books intended for your own use and primarily intended to keep track of what you've read. Only you can add to your shelves, and the only way others can see your shelves is from your profile page, if your shelves are public
- Lists: a list of books intended to be curated and shared. They can be created collaboratively, and are discoverable from book pages, the list page, search, and the profile page of the person who created the list.
- Tags: I actually forgot that tags exist. Tags are always public and let users annotate books, and provide automatically generated lists of books with shared annotations. They are only discoverable on the book page.
- Subjects: the publisher's classification of the book's topics. They come in from OpenLibrary and at this point they are just plain text and don't do anything.

In my mind, shelves and lists are the main ways of grouping books, and the important distinction is that shelves are for personal use and lists are for sharing.

**Comment by arkhi** [comment]
Thanks a lot for the explanation. :)

Based on that, I understand that shelves and lists are very similar (one dimension groups) and the only difference is the visibility and access given to others. Thinking about simplifying workflows and mental models for others, I wonder if both should not just be lists (or shelves) with options for their visibility, curation, etc. Just one simple entity with fine-grained settings.

Of course, this is only my opinion, without knowledge about the complexity to achieve such a merge, if one is even to be considered.

Is there past or current discussions on the topic to get a feeling of the average mood on this topic throughout the Bookwyrm community?

For tags, unless anybody actually uses them, I’d say they’ll mostly be source for bugs (and maintenance overload) if no one cherishes them. :)

I hope I won’t be creating frustration for questioning past decisions; my goal is really to improve UX, UI and prevent bugs by reducing what is not of use; habits!

**Comment by mouse-reeve** [comment]
no frustration at all, I really appreciate ux conversations! Collaboration and constructive feedback is a gift :)

I agree about tags, I don't use them. It was something that was suggested a few times early on (potentially as an alternative to numerical reviews). There are about 130 tags in existence created by around 30 users, so it's not a particularly in-use feature. I'd be interested to talk more with people who like tagging as a general concept to see what would make it a worthwhile feature, but personally I would be happy to remove it.

Lists and shelves are definitely similar, and I waffled on this when implementing it (#81 is the extent of the backstory). Ultimately, I created them separately because I imagine their use cases to be really different, and the workflows for those use cases is accordingly really different. For a shelf, my motivation is I want to know what books I've read and am currently reading, whereas with a list, my motivation to look at one is because I want suggestions for what to read next.

For me, imagining those cases, having it be even theoretically possible for my currently-reading shelf to show up in a public search would be a big downside. And I would find it harder to seek out lists of books to read (I rely heavily on every year's  "Queer SFF" list on goodreads for recs) if they were mixed in with people's reading logs. 

I'm curious if your understanding of what those features are for is different than mine, and/or if you have different best case scenarios about what you could use bookwyrm to do?

**Comment by mouse-reeve** [comment]
also I wonder if there's a natural way to bring more people who are using bookwyrm into conversation about what is and isn't working for them?

**Comment by arkhi** [comment]
Thank you for the conversation. :)

Warning: I’ll go full‑on with extreme positions and abstract suggestions here, not taking into consideration the amount of work implied; let’s see if that leads to fruitful outcomes. :)

> I agree about tags, I don't use them. It was something that was suggested a few times early on (potentially as an alternative to numerical reviews). There are about 130 tags in existence created by around 30 users, so it's not a particularly in-use feature. I'd be interested to talk more with people who like tagging as a general concept to see what would make it a worthwhile feature, but personally I would be happy to remove it.

One thing I like about https://inventaire.io/ (maybe others, I only have this in mind) is that it’s allowing cross DB collaboration by regularly pulling data from Wikidata but also allowing to push data to Wikidata. If feels like everybody’s winning.

I understand _Tags_ are the same as _Subjects_, not from a Bookwyrm perspective at the moment, but from a semantic point of view. Maybe editing _Subjects_ on OpenLibrary and pull(-push)ing from (and to) there (or other places) would be a more contributive alternative to having a system to maintain that replicates the same thing?

> Lists and shelves are definitely similar, and I waffled on this when implementing it (#81 is the extent of the backstory). Ultimately, I created them separately because I imagine their use cases to be really different, and the workflows for those use cases is accordingly really different. For a shelf, my motivation is I want to know what books I've read and am currently reading, whereas with a list, my motivation to look at one is because I want suggestions for what to read next.
> 
> For me, imagining those cases, having it be even theoretically possible for my currently-reading shelf to show up in a public search would be a big downside. And I would find it harder to seek out lists of books to read (I rely heavily on every year's "Queer SFF" list on goodreads for recs) if they were mixed in with people's reading logs.
> 
> I'm curious if your understanding of what those features are for is different than mine, and/or if you have different best case scenarios about what you could use bookwyrm to do?

OK; I think I understand what you mean. (yay!)

Based on what I understand and what I imagine could be, _Shelves_ could become _Book states_ and _Lists_ become the actual _Shelves_. I remember GoodReads have three _Shelves_ that are exclusive because they rely on the reading state of an _Edition_. Although the State management makes sense, I always found those being treated as _Shelves_ weird as a metadata of the _Edition_ seemed more appropriate to me. If we take the metaphor of a physical shelf, a shelf is agnostic to what book you put on it, unless one wants to have books moving all the time (and has a lot of time and space).

I understand the confusion between the current status of Bookwyrm and my hypothesis can stem from the fact a _Book_ can not currently belong to multiple shelves, as mentioned in #716. This is not a problem anymore if _Shelves_ are _States_ (and cannot be multiplied) and _Lists_ are _Shelves_.

To summarise, with _Shelves_ being called _Lists_ to be consistent with the current status of things, I imagine:

- Each object (Some Global User Settings, List, Edition, Author, Users, Statuses…) in Bookwyrm could have the standard Fediverse privacy controls:

    - Private
    - Followers
    - Unlisted
    - Public

- The privacy of the finer granular action takes precedence on previous ones, something like an <abbr title="Access Control List">ACL</abbr>? (Discard following settings if set.)

    1. Status settings (On my diary, local newspapers, TV or Internet?)
    1. Book settings (with or without a lock (personal diary))
    1. List settings (on a shelf behind an opaque or a transparent door?)
    1. User settings (displayed in my bedroom or on the sidewalk?)

    The benefit I see here is that _Lists_ could also be of authors, users (like the current _Directory_?), etc.

- Each _List_ has curation settings that allow them to be locked (behind a locked door), curated (behind a desk), or open (physically accessible).

- _Book States_ would be one of the three (independent of Lists):

    - To read
    - Reading
    - Finished

    The _Re‑read_ status mentioned in https://github.com/mouse-reeve/bookwyrm/issues/716#issuecomment-799632320 is basically a new _Reading_ with a timestamp posterior to the last _Finished_ state.

    The current state of things also frustrates me a bit as I did not find a place where I could see all my books, which would make it easier to add to lists if there was a _batch select_ option (a list with checkboxes, for instancexample) and a _Add to List_ action (or other actions).

Is this all making sense to you and is not bat‑crazy or do I sound completely bonkers? :)

**Comment by arkhi** [comment]
> also I wonder if there's a natural way to bring more people who are using bookwyrm into conversation about what is and isn't working for them?

I would say tools like Gitlab or Github are the most effective for having a focused conversation, taking decisions and linking to historical changes, but casual conversation to start issues could happen on the [Bookwyrm Matrix Channel](https://matrix.to/#/!sRDKCyKwTdfUIpLBtw:matrix.org?via=matrix.org) I mentioned a while ago, or any other mean of group conversation.

I don’t see Mastodon as a tool for chatting and organising.

Another option would be an instance of [Mobilizon](https://mobilizon.org/en/) but that might be redundant with Github.

What do you think?

**Comment by arkhi** [comment]
Thinking about https://github.com/mouse-reeve/bookwyrm/issues/798#issuecomment-808068921, a _List_ would be more to a _Shelf_ or a _Directory_ what a [_Book_ is to and _Edition_ or a _Work_](https://github.com/mouse-reeve/bookwyrm#book-data), a high‑level concept that is mostly used within the logic of the code than visible on the website. Then other less abstract lists like _Shelves_ can organise specific types of Objects.

**Comment by tastytea** [comment]
> I'd be interested to talk more with people who like tagging as a general concept to see what would make it a worthwhile feature, […]

I use tags to understand what the book is about. The book description and the publisher's subjects are often severely lacking. They can be merged with subjects in my opinion. By the way, it seems that `/tag/` pages are currently case sensitive? If they are kept they should probably be case insensitive.

**Comment by mouse-reeve** [comment]
> I understand _Tags_ are the same as _Subjects_, not from a Bookwyrm perspective at the moment, but from a semantic point of view. Maybe editing _Subjects_ on OpenLibrary and pull(-push)ing from (and to) there (or other places) would be a more contributive alternative to having a system to maintain that replicates the same thing?

Yeah, I want to learn more about how subjects are set on books, since from the outside it appears to be kind of a top down piece of metadata received from the publisher (?).

In terms of lists vs shelves, let me try to tell back my understanding of what you're suggesting based on what bookwyrm currently does, so we can see if I understand you fully. 

The current bookwyrm behavior for the **List** model:
 - holds books
 - has curation settings
 - has privacy settings applied to the list itself

Your suggested change for lists:
 - Re-name them to "shelves"
 - hold any type of object
 - have privacy settings applied to the objects as well as the list

The current bookwyrm behavior for the **Shelf** model:
 - holds books
 - has privacy settings
 - used to determine the current "state" of the book (to-read/currently reading/read)
 - users can create arbitrary shelves to represent whatever other states they want

In your paradigm, shelves would be removed.

The current bookwyrm behavior for the **Readthrough** model:
- Represents an instance that the user read a book
- Contains timestamps for start date, any progress updates, and completion date
- Created and updated automatically with user approval when books are moved between currently ready and read shelves
- Automatically created during csv imports when the data is available

In your paradigm, this would entirely replace the need for shelves for tracking book state.

Before I get into anything else, I just want to make sure that's accurate to what you're thinking, so let me know if I'm off base.

**Comment by arkhi** [comment]
I think you got it right, with maybe nuances:

> Your suggested change for lists:
> 
> Re-name them to "shelves"
> hold any type of object
> have privacy settings applied to the objects as well as the list

I am thinking of a _List_ model that groups any object, with different appellations for the type of content they group. _Shelf_ for Books, _Directory_ for people, maybe, _Notes_ for Readthroughs, etc.

Not sure if that’s a better or worse idea to have one abstraction for all, with refined appellations for types.

> In your paradigm, shelves would be removed.

Yes, they would become states for each book.

I guess those states are what Readthroughs currently are at their extremes (before the read, during the read, after the read). Maybe current shelves could be part of Readthroughs in the end? I think that’s what you mean with:

> In your paradigm, this would entirely replace the need for shelves for tracking book state.

**Comment by mouse-reeve** [comment]
I'm not sure I understand the appeal of a list that can have anything on it? I feel like that level of unstructured-ness makes it hard to know how to use features, and difficult to make them useful. For example, with a list of just books, it's clear that you should add books to them, and you can do things like sort and filter the list by book attributes, or perform bulk actions over the list of books. 

Maybe this is a tradeoff between giving the user power to do more things, and giving the user more guidance and simplicity about what the app should do. I tend towards the latter end - my goal is to create a UI that facilitates certain types of activities, rather than being more open-ended. One of the main design constraints that reflects that is that you can't post statuses unless they are about books -- there's no technical reason you couldn't post on BookWyrm the same way you might post on Mastodon, but I think the value in being on BookWyrm as opposed to Mastodon is that it structures user behavior in a particular way (ie, around books). 

In terms of the abstraction, I'm not sure what, concretely, it would mean for that to exist. I think _conceptually_, the abstract concept of a list of objects already exists (in lists, shelves, the directory, user's posts, reviews of books, etc). There isn't a shared database model underlying the various models that contain lists of objects, and I'm not sure what kind of benefit that would provide. 

I suppose I'm thinking about what you're suggesting in two categories - renaming existing concepts/database models, vs changing the schema for how user book data is stored - and getting a bit confused about which is which.

**Comment by arkhi** [comment]
> I'm not sure I understand the appeal of a list that can have anything on it? I feel like that level of unstructured-ness makes it hard to know how to use features, and difficult to make them useful.

I think there are two perspectives competing with each other here:

- The overall structure of the Objects (backend, DB),
- The structure of how the data is presented (UI, UX, frontend).

**On the code side**, the proposal I am thinking of is organising _Items_ (books, users, etc.) into _Lists_ in a generic semantic way, with the attributes we mentioned:

- has curation settings
- has privacy settings applied to the list itself

Each type of list can inherit from this generic _List_ or add more attributes if need be.

**On the frontend side** (what the user interacts with), the type of list is presented as needs be (Shelf, Directory, etc.).

This is just a way to avoid duplicating behaviours and structure data in a way that might be more easy to test.

---
> It's not clear how and why to use tags, and a solution would be to remove them

Agreed. Along with the fact they seem redundant with _Subjects_ from my perspective.

> The difference between how lists and shelves work is unclear from the interface

Agreed. I find them redundant as well.

> The term "Shelf" creates a metaphor to physical shelves that doesn't map on to what "shelves" in the app do (keep track of book state). A possible solution would be using the wording "Your books" instead of "Your shelves"

Mostly. They could be called _Reading State_ or be part of the Readthrough process (before the read, during the read, after the read).

> Users might want to make lists of things besides books

I was not thinking about users in this case, just about a way to structure the different types of objects that can share similar paradigms, not providing a generic _List_ feature.

**Comment by mouse-reeve** [comment]
Okay, I guess what I'm having trouble understanding is how your vision of reading states is different than the current system? Do you have a specific idea of what it would look like to start and finish reading a book in the UI, and to find books you've read?

**Comment by arkhi** [comment]
Mmm… I imagine a UI with a “My books” menu entry that you mentioned earlier, with four filters:

- All (default)
- To read
- Reading
- Finished

That’s it. I understand this would remove ambiguity between _States_ (fixed number) and _Shelves_ (which can be added by the user) in the current setup.

The default might also be user-customisable.

**Comment by mouse-reeve** [comment]
Okay, I've made a few changes based on this conversation. I changed the wording around "shelves" in the UI, added a default view of all your books, and removed part of the UI for the tags feature (as a small step towards removing the feature).

**Comment by mouse-reeve** [comment]
I'm closing this as part of trying to get a handle on the issue queue - I think at this point, it will be more manageable to address ideas related to this in new, more focussed issues. Thank you for the conversation ❤️
