### ISSUE TITLE
Make BookWyrm theme-able

### ISSUE THREAD

**Issue by mouse-reeve** [bookwyrm-social/bookwyrm#815]
It would be great to let admins create a default css theme for their instances, and let users select a theme at their preference. Dark mode!

I think this involves a number of steps, which can be handled atomically:
 - [x] Switching to a compiled-from-sass version of the bulma styles and custom css
 - [ ] Update the css colors used in the templates to be semantic rather than color-names
 - [x] Create a theme file
 - [ ] Give admins a way to set available and default themes
 - [ ] Give users a way to select their own theme

**Comment by seniorm0ment** [comment]
I'd also really like to see a built in "lightweight" theme built in. This can give users the ability to swap to a theme that can perform better on lower end hardware, and internet connections. It can also provide a more "classic internet feel" feel if they wish, instead of the more modern feel.
Ideally allow the "lightweight" theme to work without Javascript as well if possible.

I think natively providing BookWyrm with a "modern" theme (like the current), and a "lightweight"/"classic" theme (like described below), would be amazing. Then admins can furthermore customize if they wish from there. But at least users wouldn't have to rely on admins to create/add a lightweight theme just to use that.
______

To provide an idea of what I mean by classic/lightweight, I'd suggest taking a look at Nitter's default interface. 
https://nitter.kavin.rocks/elonmusk (if that interface is down check out any of the others: https://github.com/zedeus/nitter/wiki/Instances).
It's 60KB (vs Twitter's theme of 784KB), and can work without JavaScript enabled.
