### ISSUE TITLE
Sitewide footer is buried by user's feed

### ISSUE THREAD

**Issue by binyamin** [bookwyrm-social/bookwyrm#917]
Currently, the only way to learn anything about Bookwyrm, at least when logged-in, is to scroll down below the user feed. This can be tedious, and uninviting.

Suggestion: Move it to the sidebar (figure 1), or fit the links into the top navbar.

###### Figure 1
![figure 1](https://user-images.githubusercontent.com/39805353/114235950-e85f7180-994e-11eb-8a65-9ab6c92b6db6.png)

**Comment by mouse-reeve** [comment]
Thank you! I think it makes sense for this to be in the sidebar. The one issue is that as it stands, the sidebar appears above the feed on mobile, so it would be a hassle for mobile users to scroll past that info every time. Screenreader users will also hit the sidebar before the feed.

**Comment by arkhi** [comment]
Hello @binyamin. I understand what your issue describes but I fail to understand what problem your proposal wants to solve.

I think it is a standard pattern to have this kind of information at the bottom of a document, unless there is some sort of infinite scrolling.

From a UX perspective, I think the information you describe is particularly important for people who are not already registered, to help them understand what joining the instance entails. Once they joined, the information in this footer would only be accessed on very few occasions; what do you think?

I would second putting a donation button somewhere in the user menu though, maybe a button below the _Logout_ (with enough space to not logout or donate when trying to achieve the opposite). :)

**Comment by mouse-reeve** [comment]
I've thought about this and I think I agree with @arkhi that since the app isn't using infinite scroll, it makes sense for the footer content to remain where it is. Since this was files, the feed display has gotten more compact, which hopefully addresses the pain point of there being too much scrolling to get to the bottom of the page. In theory, the content in the footer should be information you would want very infrequently.
