### ISSUE TITLE
Social interactions: which ones are needed or desirable?

### ISSUE THREAD

**Issue by arkhi** [bookwyrm-social/bookwyrm#945]
As those interactions can become toxic addictions, shall mechanisms to disable them or “health feedback” should be provided?

I would recommend [_Your undivided attention_](https://www.humanetech.com/podcast) as an example of what can be done. I can’t find the right episode back, but things like a notification stating the amount of time spent on the website can help some people to break up the addiction by bringing friction.

> > Naturally, the question that can be asked is _is this really necessary to display someone's following_? But let's say it's out of scope for this PR 😄
> 
> I'd be happy to have a deeper conversation on this in a separate issue! My short answer is, I find it handy to know how socially connected to someone I am when evaluating how comfortable I feel with strangers.

_Originally posted by @mouse-reeve in https://github.com/bookwyrm-social/bookwyrm/issues/935#issuecomment-820743246_

**Comment by arkhi** [comment]
ping @joachimesque

**Comment by arkhi** [comment]
> I'm not sure what you mean specifically about implementing software-localizations tools - Gettext is what is currently in use. I definitely support adding things to the documentation, though!

I mean an online tool to specifically collaborate on localising a software, like Transifex, for example.

> When "remove" is used, it's in the sense of "does not belong to its parent any more" not in the sense of "deleted from the database".

Yep. Actually _Remove_ should be _Retirer_ and _Delete_ should be _Supprimer_.

> So if there's a gender neutral way of saying things that is accessible and isn't so out of standard usage that it would confuse people, I prefer that. Introducing an entire new neutral grammatical gender and inventing declensions for it, for example, would probably be a step too far wink.

Aaaah… You’re breaking my heart! :) I was going to propose some work to come up with proper neologisms based on greek roots. This is mentioned in @juliemoynat’s [excellent article](https://www.lalutineduweb.fr/ecriture-inclusive-accessibilite-numerique-jetdv2020/) (in French) @joachimesque linked, and I can see the benefit of creating new words or grammar constructions over “demoting” from male to neutral since those words would always keep a male scent for generations anyway.

**Comment by mouse-reeve** [comment]
Yeah! I've thought some about what kind of activities BookWyrm should facilitate, and where to introduce friction, and it would be great to get outside perspectives, especially now that more people are actually _using_ the service. I believe I linked https://runyourown.social/ in the README as well, and it's a philosophical cornerstone for me.

Here's a rough breakdown of my thoughts:

### Incentives
A foundational problem with corporate social media is that, at the end of the day, their goal is growth and user engagement, no matter what the engagement is or how the growth impacts the community. Venture capital, ad revenue, and selling user data are all financial incentive systems that entrench this.

I've tried to guard against this by using an anti-capitalist software license, not showing ads or building in systems for showing ads, and not seeking venture funding or taking money that comes with those kinds of incentives attached. Of course, the Patreon is a long long way from being a financially sustainable way to support longer-term development, but that's the situation right now.

### Scale
I think a major reason growth is harmful to user experience is that it creates huge, unmanageable spaces in which people don't feel a sense of comfort or trust. There are a few interrelated problems with unchecked growth:
- There's a limit to how many people you can know and feel in community with - this is the idea behind Dunbar's number, and I think Darius really nails it: https://runyourown.social/#keep-it-small. In my mind this is the most core, fundamental principal.
- It becomes hard or impossible to carefully and humanly moderate at scale. This is a problem for users, who won't feel safe, heard, and cared for, and for moderators, who will be exhausted, overwhelmed, and potentially traumatized. Additionally, one set of rules has to apply to everyone, regardless of their varying needs or interests.
- Eventually you end up in places like Twitter and Facebook are, with radicalization and polarization in a way that facilitates real world violence and harm.
- Running the service becomes harder and requires more server capacity, fancy load balancing whatever systems, and system administration labor, all of which amounts to needing more money and more professionalized work.

This is why I feel invested in a federated model - we can have small, autonomous communities that can self-regulate and foster trust and care, interacting with other communities only insofar as it is a positive experience which is mutually enriching, and opt out of interactions with users and communities that are undesirable. Neither the technology nor the interpersonal community need to scale along with the network.

A feature BookWyrm doesn't currently have that would really help here is local-only posting (#559).

### Stickiness and friction
Large social media sites have huge, systemic problems with people getting sucked in or "addicted", and ending up feeling worse in the moment and experience larger detriments to their mental health as a result. That's incredibly fucked up! It would be much better for no one to use BookWyrm than for people to use it and be worse off on the whole because of it. 

There are a few ways this plays out, at least in my own experience:
- Feeding into and hijacking intense emotional reactions. In my experience this is what Twitter is all about, showing you upsetting content, and then redirecting your emotional response into more tweeting, which spreads the emotional reaction to your network and so on and so forth. No constructive progress is made on the original upsetting thing, everyone involved feels alienated and distressed, and Twitter is allowed to frame being on twitter as the only available form of praxis.
- Infinite distraction. Instagram's discover view absolutely annihilates me with this, which is why I don't use Instagram. By infinite distraction I mean interfaces that provide an endless feed of colorful, easily digestible snippets of media that can be consumed with almost no effort and without end. 
- Gamification. This might be the wrong word for this, but what I mean is, creating metrics and rewarding users for using the app more as an end unto itself. Trying to get more followers, retweets, and likes on twitter, for example. I find it very telling that getting "ratio'ed" on twitter (when a tweet has a proportionally large number of replies relative to likes and retweets) is a bad thing -- I would much rather have an extended conversation about a book than get a lot of passive affirmations about my opinions on it. 

There are a few aspects of BookWyrm that I hope avoid these patterns:
- Pagination instead of infinite scroll adds points of friction when consuming the activity feed
- Boost and fav counts aren't shown, so it's harder to "gameify" accumulating them
- Posts can be (and often are) long and in depth
- There are ways of posting that don't forefront an opinion - reviewing asks a user to take a concrete stance on a book and judge it, but marking a book as want to read, commenting, and quoting from books are all forms of posting that forefront taking interest in the content of a book, rather than necessarily expressing a definite opinion about it. 

Showing follower/following counts is an interesting one! I know someone mentioned in a different conversation that seeing those numbers can be a useful heuristic for evaluating how legitimate an account is. Personally, I like to look at how many mutuals I have with a stranger as a quick way to evaluate how comfortable I feel interacting with them. But I certainly do _not_ want having a lot of followers to be a motivating force! A possible solution is to only show mutual connections, rather than the whole number.

---

Anyway that is a very long response! Maybe I'll try and turn it into part of the documentation 🤔. 

### Actually actionable ideas in that very long block of text
- BookWyrm should have local-only posting
- Display of follower/following counts and lists could be tweaked in some way, such as only showing mutuals connections

**Comment by joachimesque** [comment]
I like the patterns you inserted in the app to avoid weaponize it in that war against attention.

> Showing follower/following counts is an interesting one! I know someone mentioned in a different conversation that seeing those numbers can be a useful heuristic for evaluating how legitimate an account is.

This asks an interesting question: can we think of other ways to check on the legitimacy of an account? Would it be possible to provide other info, or the same info in a less precise way? "This person is not connected at all", "This person has a lot of activity"?

> Personally, I like to look at how many mutuals I have with a stranger as a quick way to evaluate how comfortable I feel interacting with them. But I certainly do not want having a lot of followers to be a motivating force! A possible solution is to only show mutual connections, rather than the whole number.

IMO, displaying mutuals is more useful than the number of followers/folowing. These numbers are always compared to each other. Are you a reader (follows more than is followed) or a broadcaster (followed more than follows)? I don't care, and I don't especially want people to have a wrong idea about me because of these numbers.

> Display of follower/following counts and lists could be tweaked in some way, such as only showing mutuals connections

I'm in favour of that idea! I haven't seen how "mutual connexions" is defined on Bookwyrm. Is it:

- People that follow me, and follow the Other Person?
- People that I follow, who follow the Other Person?
- People that the Other Person and I both follow?
- People that are followed by both the Other Person and I?
- People who follow/are followed by me and follow/are followed by the Other Person?

**Comment by mouse-reeve** [comment]
> I'm in favour of that idea! I haven't seen how "mutual connexions" is defined on Bookwyrm. Is it:
> 
> * People that follow me, and follow the Other Person?
> * People that I follow, who follow the Other Person?
> * People that the Other Person and I both follow?
> * People that are followed by both the Other Person and I?
> * People who follow/are followed by me and follow/are followed by the Other Person?

I've been using "people that I follow, who follow the other person" (although there was a bug in how I computed that which is fixed as of this morning)

**Comment by mouse-reeve** [comment]
I really appreciate all the thought here! I'm going to close this issue so that ongoing discussion on the topic can happen in specific issues
